import { useEffect, useRef } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import type { ReadingQuestion, ReadingState } from "./reading.types"
import { readingAlignmentClass, readingTextForDisplay } from "./reading.utils"

export function ReadingPanel({ question, state, emphasizeCurrent, emphasizeFirstParagraph, reducedMotion }: { question: ReadingQuestion; state: ReadingState; emphasizeCurrent: boolean; emphasizeFirstParagraph: boolean; reducedMotion: boolean }) {
  const paragraphRefs = useRef<Array<HTMLParagraphElement | null>>([])
  useEffect(() => { if (question.progressMode !== "MANUAL_SEGMENTS") return; const target = paragraphRefs.current[state.currentParagraphIndex]; if (!target) return; target.scrollIntoView({ block: "center", behavior: reducedMotion ? "auto" : "smooth" }) }, [question.progressMode, reducedMotion, state.currentParagraphIndex])
  return <Card className="overflow-hidden"><CardHeader className="space-y-2"><div className="flex flex-wrap items-center gap-2"><Badge variant="secondary">{question.contentMode === "PARAGRAPH" ? "Panel bacaan" : "Bacaan ringkas"}</Badge>{question.progressMode === "MANUAL_SEGMENTS" ? <Badge variant="outline">Perenggan {state.currentParagraphIndex + 1} / {question.paragraphs.length}</Badge> : null}</div>{question.title ? <CardTitle className="text-xl sm:text-2xl">{question.title}</CardTitle> : null}</CardHeader><CardContent>{question.contentMode === "PARAGRAPH" ? <div className="max-h-[28rem] space-y-4 overflow-y-auto rounded-xl border bg-muted/20 p-4 sm:p-6" aria-label="Panel teks bacaan">{question.paragraphs.map((paragraph, index) => { const isCurrent = index === state.currentParagraphIndex; const isCompleted = index < state.currentParagraphIndex; const emphasized = (emphasizeCurrent && isCurrent) || (emphasizeFirstParagraph && index === 0); return <p key={paragraph.id} ref={(element) => { paragraphRefs.current[index] = element }} className={`${readingAlignmentClass(question)} rounded-xl px-3 py-2 transition-colors motion-reduce:transition-none ${isCompleted ? "text-muted-foreground" : "text-foreground"} ${emphasized ? "bg-primary/10 ring-1 ring-primary/30" : ""}`} style={{ fontSize: `${Math.round(question.display.fontSize * state.zoomPercent / 100)}px`, lineHeight: question.display.lineHeight }}>{question.display.showParagraphNumbers ? <span className="mr-2 font-semibold text-primary">{paragraph.sequence}.</span> : null}{paragraph.text}</p> })}</div> : <div className={`rounded-2xl border bg-muted/20 p-6 sm:p-8 ${readingAlignmentClass(question)}`} style={{ fontSize: `${Math.round(question.display.fontSize * state.zoomPercent / 100)}px`, lineHeight: question.display.lineHeight }}><p className={`${emphasizeCurrent ? "rounded-xl bg-primary/10 px-4 py-3 ring-1 ring-primary/30" : ""}`}>{readingTextForDisplay(question)}</p></div>}</CardContent></Card>
}
