import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { READING_COMPREHENSION_MAX_BYTES, ReadingComprehensionContractError, readingComprehensionAuditSummary, readingComprehensionPreviewConfiguration, validateReadingComprehensionConfiguration } from "../src/contracts/reading-comprehension.contract.js";

const mediaKey = "activity-image/2026/07/00000000-0000-4000-8000-000000000301.png";
function valid(): unknown { return { readingComprehension: { passage: { title: "Baju Ali", content: "Ali memakai baju baharu.", media: [{ key: mediaKey }] }, questions: [{ id: "Q1", type: "MULTIPLE_CHOICE", question: "Apakah yang Ali pakai?", required: true, marks: 5, options: [{ id: "A", label: "A", content: "Baju", isCorrect: true }, { id: "B", label: "B", content: "Buku", isCorrect: false }] }, { id: "Q2", type: "TRUE_FALSE", question: "Ali memakai baju.", required: true, marks: 3, options: [{ id: "T", label: "BETUL", content: "Betul", isCorrect: true }, { id: "F", label: "SALAH", content: "Salah", isCorrect: false }] }, { id: "Q3", type: "SHORT_TEXT", question: "Siapakah memakai baju?", required: true, marks: 4, acceptableAnswers: ["Ali"] }], showPassageFirst: true, allowPassageDuringQuestions: true, randomizeQuestions: false, showQuestionNumbers: true, showImmediateFeedback: false, allowRetry: true } }; }
function clone(value: unknown): Record<string, unknown> { return JSON.parse(JSON.stringify(value)) as Record<string, unknown>; }
function definition(value: Record<string, unknown>): Record<string, unknown> { return value.readingComprehension as Record<string, unknown>; }
function rejects(value: unknown, issue: string): void { assert.throws(() => validateReadingComprehensionConfiguration(value), (caught: unknown) => caught instanceof ReadingComprehensionContractError && caught.issues.includes(issue as never)); }
test("Reading Comprehension accepts passage, MCQ, True/False, and Short Text", () => { const parsed = validateReadingComprehensionConfiguration(valid()); assert.equal(parsed.readingComprehension.questions.length, 3); assert.equal(parsed.readingComprehension.questions[2]?.acceptableAnswers[0], "Ali"); });
test("Reading Comprehension rejects duplicate question IDs, duplicate answers, and invalid options", () => { const duplicate = clone(valid()); (definition(duplicate).questions as Array<Record<string, unknown>>)[1]!.id = "Q1"; rejects(duplicate, "READING_COMPREHENSION_QUESTION_ID_DUPLICATE"); const answers = clone(valid()); (definition(answers).questions as Array<Record<string, unknown>>)[2]!.acceptableAnswers = ["Ali", " ali "]; rejects(answers, "READING_COMPREHENSION_ANSWERS_INVALID"); const mcq = clone(valid()); (definition(mcq).questions as Array<Record<string, unknown>>)[0]!.options = [{ id: "A", label: "A", content: "Baju", isCorrect: true }]; rejects(mcq, "READING_COMPREHENSION_OPTIONS_INVALID"); const tf = clone(valid()); (definition(tf).questions as Array<Record<string, unknown>>)[1]!.options = [{ id: "T", label: "YA", content: "Ya", isCorrect: true }, { id: "F", label: "TIDAK", content: "Tidak", isCorrect: false }]; rejects(tf, "READING_COMPREHENSION_OPTIONS_INVALID"); });
test("Reading Comprehension validates passage, questions, explanations, and unsafe JSON", () => { const passage = clone(valid()); delete definition(passage).passage; rejects(passage, "READING_COMPREHENSION_PASSAGE_INVALID"); const empty = clone(valid()); (definition(empty).questions as Array<Record<string, unknown>>)[0]!.question = " "; rejects(empty, "READING_COMPREHENSION_QUESTION_INVALID"); const oversized = clone(valid()); (definition(oversized).passage as Record<string, unknown>).content = "a".repeat(3001); rejects(oversized, "READING_COMPREHENSION_PASSAGE_INVALID"); const explanation = clone(valid()); (definition(explanation).questions as Array<Record<string, unknown>>)[0]!.explanation = "a".repeat(501); rejects(explanation, "READING_COMPREHENSION_QUESTION_INVALID"); const html = clone(valid()); (definition(html).passage as Record<string, unknown>).content = "<b>Ali</b>"; rejects(html, "READING_COMPREHENSION_UNSAFE_CONTENT"); const url = clone(valid()); (definition(url).passage as Record<string, unknown>).content = "https://example.test"; rejects(url, "READING_COMPREHENSION_UNSAFE_CONTENT"); const oversizedJson = clone(valid()); (definition(oversizedJson).passage as Record<string, unknown>).content = "a".repeat(READING_COMPREHENSION_MAX_BYTES); rejects(oversizedJson, "READING_COMPREHENSION_CONFIGURATION_TOO_LARGE"); });
test("Reading Comprehension preview preserves stored question order and audit never includes answers", () => { const contract = validateReadingComprehensionConfiguration(valid()); const preview = readingComprehensionPreviewConfiguration(contract, new Map([[mediaKey, { url: "/media/passage", mimeType: "image/png", altText: "Baju", label: null }]])); assert.deepEqual(preview.readingComprehension.questions.map((question) => question.id), ["Q1", "Q2", "Q3"]); assert.equal(preview.readingComprehension.passage.media[0]?.url, "/media/passage"); assert.deepEqual(readingComprehensionAuditSummary(contract), { questionCount: 3, passageLength: 24, questionTypes: ["MULTIPLE_CHOICE", "TRUE_FALSE", "SHORT_TEXT"] }); });
test("Reading Comprehension workflow blocks malformed contracts and marks legacy items incomplete", async () => { const service = await readFile(new URL("../src/services/digitalActivity.service.ts", import.meta.url), "utf8"); assert.match(service, /READING_COMPREHENSION_CONTRACT_INVALID/); assert.match(service, /EXPLICIT_READING_COMPREHENSION_CONTRACT_REQUIRED/); assert.match(service, /activityTemplate\.code === "READING_COMPREHENSION"/); });
test("Reading Comprehension adds no Prisma models", async () => { const schema = await readFile(new URL("../prisma/schema.prisma", import.meta.url), "utf8"); assert.doesNotMatch(schema, /ReadingComprehension(?:Attempt|Submission|Assignment|Assessment|AI)/); });
