import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { VoiceRecordingContractError, voiceRecordingAuditSummary, voiceRecordingPreviewConfiguration, validateVoiceRecordingConfiguration } from "../src/contracts/voice-recording.contract.js";

const mediaKey = "activity-audio/2026/07/00000000-0000-4000-8000-000000000401.mp3";
function valid(): unknown { return { voiceRecording: { prompt: { title: "Baca", content: "Baca ayat ini dengan jelas.", media: [{ key: mediaKey }] }, recording: { minimumDurationSeconds: 3, maximumDurationSeconds: 60, maximumAttempts: 3, allowPlayback: true, allowReRecord: true, autoStop: true, autoSubmitOnFinish: false, required: true }, instructions: "Tekan mula untuk merakam." } }; }
function clone(value: unknown): Record<string, unknown> { return JSON.parse(JSON.stringify(value)) as Record<string, unknown>; }
function definition(value: Record<string, unknown>): Record<string, unknown> { return value.voiceRecording as Record<string, unknown>; }
function rejects(value: unknown, issue: string): void { assert.throws(() => validateVoiceRecordingConfiguration(value), (caught: unknown) => caught instanceof VoiceRecordingContractError && caught.issues.includes(issue as never)); }
test("Voice Recording accepts normalized prompt and valid recording configuration", () => { const parsed = validateVoiceRecordingConfiguration(valid()); assert.equal(parsed.voiceRecording.recording.minimumDurationSeconds, 3); assert.equal(parsed.voiceRecording.prompt.content, "Baca ayat ini dengan jelas."); });
test("Voice Recording rejects invalid durations and attempts", () => { const minimum = clone(valid()); (definition(minimum).recording as Record<string, unknown>).minimumDurationSeconds = 0; rejects(minimum, "VOICE_RECORDING_RECORDING_INVALID"); const maximum = clone(valid()); (definition(maximum).recording as Record<string, unknown>).maximumDurationSeconds = 2; rejects(maximum, "VOICE_RECORDING_RECORDING_INVALID"); const attempts = clone(valid()); (definition(attempts).recording as Record<string, unknown>).maximumAttempts = 21; rejects(attempts, "VOICE_RECORDING_RECORDING_INVALID"); });
test("Voice Recording rejects oversized and unsafe prompt or instructions", () => { const prompt = clone(valid()); (definition(prompt).prompt as Record<string, unknown>).content = "a".repeat(3001); rejects(prompt, "VOICE_RECORDING_PROMPT_INVALID"); const instructions = clone(valid()); definition(instructions).instructions = "a".repeat(1001); rejects(instructions, "VOICE_RECORDING_INSTRUCTIONS_INVALID"); const html = clone(valid()); (definition(html).prompt as Record<string, unknown>).content = "<b>Baca</b>"; rejects(html, "VOICE_RECORDING_UNSAFE_CONTENT"); const script = clone(valid()); definition(script).instructions = "javascript:alert(1)"; rejects(script, "VOICE_RECORDING_UNSAFE_CONTENT"); const url = clone(valid()); definition(url).instructions = "https://example.test"; rejects(url, "VOICE_RECORDING_UNSAFE_CONTENT"); });
test("Voice Recording preview and audit expose only contract settings and safe media", () => { const contract = validateVoiceRecordingConfiguration(valid()); const preview = voiceRecordingPreviewConfiguration(contract, new Map([[mediaKey, { url: "/media/audio", mimeType: "audio/mpeg", altText: "Arahan", label: "/private/tmp/audio.mp3" }]])); assert.equal(preview.voiceRecording.prompt.media[0]?.url, "/media/audio"); assert.equal(preview.voiceRecording.prompt.media[0]?.label, null); assert.equal(preview.voiceRecording.recording.maximumAttempts, 3); assert.deepEqual(voiceRecordingAuditSummary(contract), { minimumDurationSeconds: 3, maximumDurationSeconds: 60, maximumAttempts: 3 }); });
test("Voice Recording workflow blocks malformed contracts and marks legacy items incomplete", async () => { const service = await readFile(new URL("../src/services/digitalActivity.service.ts", import.meta.url), "utf8"); assert.match(service, /VOICE_RECORDING_CONTRACT_INVALID/); assert.match(service, /EXPLICIT_VOICE_RECORDING_CONTRACT_REQUIRED/); assert.match(service, /rendererKey === "voice-recording"/); });
test("Voice Recording adds no persistence or assessment models", async () => { const schema = await readFile(new URL("../prisma/schema.prisma", import.meta.url), "utf8"); assert.doesNotMatch(schema, /VoiceRecording(?:Attempt|Submission|Assignment|Assessment|AI|Speech)/); });
