import { Link } from "react-router-dom";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/shared/StatusBadge";
import type { StudentRecord } from "@/features/student/types/student.types";
import { recordId, valueText } from "@/features/student/utils/student-record";
export function StudentStats({ items }: { items: { label: string; value: unknown }[] }) { return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{items.map((item)=><Card key={item.label} className="border-primary/20"><CardHeader className="pb-2"><CardDescription>{item.label}</CardDescription><CardTitle className="text-3xl">{valueText(item.value)}</CardTitle></CardHeader></Card>)}</div>; }
export function AssignmentCards({ rows }: { rows: StudentRecord[] }) { return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map((row)=>{const activity=typeof row.activity === "object" && row.activity !== null ? row.activity as StudentRecord : {};const canOpen=row.canOpen===true;return <Card key={recordId(row)} className="border-primary/20"><CardHeader><CardTitle>{valueText(row.title)}</CardTitle><CardDescription>{valueText(activity.title)} · {valueText(row.availabilityStatus)}</CardDescription></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">Tarikh akhir: {valueText(row.dueAt)}</p>{canOpen?<Button asChild className="w-full"><Link to={`/murid/tugasan/${recordId(row)}`}>Mula atau sambung</Link></Button>:<Button className="w-full" disabled>Tidak tersedia</Button>}</CardContent></Card>})}</div>; }
export function StudentCards({ rows, detailPath, empty }: { rows: StudentRecord[]; detailPath?: (row: StudentRecord)=>string; empty:string }) { if(!rows.length)return <p className="rounded-lg border border-dashed border-border p-8 text-center text-muted-foreground">{empty}</p>; return <div className="grid gap-4 md:grid-cols-2">{rows.map((row)=><Card key={recordId(row)}><CardHeader><CardTitle className="text-base">{valueText(row.title ?? row.assignmentTitle ?? row.activityTitle ?? row.id)}</CardTitle><CardDescription>{valueText(row.submittedAt ?? row.assessedAt ?? row.createdAt)}</CardDescription></CardHeader><CardContent className="flex items-center justify-between gap-2">{typeof row.status==="string"?<StatusBadge status={row.status}/>:<span/>}{detailPath?<Button size="sm" asChild><Link to={detailPath(row)}>Lihat</Link></Button>:null}</CardContent></Card>)}</div>; }
