import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeader } from "@/components/shared/PageHeader";
import { ErrorState } from "@/components/shared/ErrorState";
import { LoadingSpinner } from "@/components/shared/LoadingSpinner";
import { notificationPost, notificationPreferences, notifications, updateNotificationPreferences, type NotificationRecord } from "@/features/notifications/api/notifications.api";
const text=(v:unknown)=>typeof v==="string"||typeof v==="number"?String(v):"—";
export function NotificationCentrePage(){const client=useQueryClient();const q=useQuery({queryKey:["notifications","centre"],queryFn:()=>notifications("?limit=20")});const action=useMutation({mutationFn:({path,body}:{path:string;body?:NotificationRecord})=>notificationPost(path,body),onSuccess:()=>void client.invalidateQueries({queryKey:["notifications"]})});if(q.isLoading)return <LoadingSpinner label="Memuatkan notifikasi..."/>;if(q.error)return <ErrorState actionLabel="Cuba lagi" onAction={()=>void q.refetch()}/>;return <main className="space-y-6"><PageHeader title="Notifikasi" actions={<Button disabled={action.isPending} onClick={()=>action.mutate({path:"/notifications/read-all"})}>Tanda semua dibaca</Button>}/><div className="space-y-3">{q.data?.notifications.map(n=><Card key={text(n.id)}><CardHeader><CardTitle className="text-base">{text(n.title)}</CardTitle><CardDescription>{text(n.createdAt)} · {text(n.priority)}</CardDescription></CardHeader><CardContent className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm">{text(n.body)}</p><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>action.mutate({path:"/notifications/read",body:{notificationIds:[text(n.id)]}})}>Dibaca</Button><Button size="sm" variant="outline" onClick={()=>action.mutate({path:"/notifications/archive",body:{notificationIds:[text(n.id)]}})}>Arkib</Button></div></CardContent></Card>)}</div></main>}
export function NotificationPreferencesPage(){const q=useQuery({queryKey:["notifications","preferences"],queryFn:notificationPreferences});const save=useMutation({mutationFn:updateNotificationPreferences});if(q.isLoading)return <LoadingSpinner label="Memuatkan keutamaan..."/>;if(q.error)return <ErrorState/>;const fields=["assignments","assessments","announcements","ai","parentProgress","reminders","security","emailEnabled","inAppEnabled"];return <main className="space-y-6"><PageHeader title="Keutamaan Notifikasi"/><Card><CardContent className="space-y-3 p-6">{fields.map(key=><label key={key} className="flex items-center justify-between gap-3"><span>{key}</span><input type="checkbox" defaultChecked={q.data?.[key]===true} onChange={(e)=>save.mutate({[key]:e.target.checked})}/></label>)}</CardContent></Card></main>}
