import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/shared/PageHeader";
import { ErrorState } from "@/components/shared/ErrorState";
import { LoadingSpinner } from "@/components/shared/LoadingSpinner";
import { ActivityErrorState } from "@/features/activity-player/components/ErrorState";
import { StudentCards, StudentStats, AssignmentCards } from "@/features/student/components/StudentComponents";
import { useDelivery, useStudentDashboard, useStudentDetail, useStudentList, useStudentPost } from "@/features/student/hooks/use-student";
import type { StudentResource } from "@/features/student/types/student.types";
import { isRecord, safeEntries, valueText } from "@/features/student/utils/student-record";
const labels:Record<StudentResource,string>={assignments:"Tugasan Saya",submissions:"Penghantaran Saya",assessments:"Keputusan Saya",notifications:"Notifikasi",announcements:"Pengumuman"};
function State({loading,error,retry}:{loading:boolean;error:unknown;retry:()=>void}){if(loading)return <div className="grid min-h-48 place-items-center"><LoadingSpinner label="Memuatkan..."/></div>;if(error)return <ErrorState title="Tidak dapat memuatkan data" description="Sila cuba lagi." actionLabel="Cuba lagi" onAction={retry}/>;return null;}
export function StudentDashboardPage(){const q=useStudentDashboard();const data=q.data??{};const analytics=isRecord(data.analytics)?data.analytics:{};return <main className="space-y-6"><PageHeader title="Hai, Murid!" description="Mari teruskan pembelajaran hari ini."/><State loading={q.isLoading} error={q.error} retry={()=>void q.refetch()}/>{!q.isLoading&&!q.error?<><StudentStats items={[{label:"Tugasan",value:isRecord(analytics.assignments)?analytics.assignments.total:"—"},{label:"Kemajuan",value:isRecord(analytics.mastery)?analytics.mastery.currentProgress:"—"},{label:"Trend",value:isRecord(analytics.mastery)?analytics.mastery.trend:"—"}]}/><Card><CardHeader><CardTitle>Tugasan Hari Ini</CardTitle><CardDescription>Pilih tugasan yang tersedia untuk mula.</CardDescription></CardHeader><CardContent><Button asChild><Link to="/murid/tugasan">Lihat tugasan saya</Link></Button></CardContent></Card></>:null}</main>}
export function StudentListPage({resource}:{resource:StudentResource}){const [search,setSearch]=useState("");const q=useStudentList(resource,{page:1,limit:20,search:search||undefined});const detail=resource==="submissions"?(r:{id?:unknown})=>`/murid/penghantaran/${valueText(r.id)}`:resource==="assessments"?(r:{id?:unknown})=>`/murid/penilaian/${valueText(r.id)}`:undefined;return <main className="space-y-6"><PageHeader title={labels[resource]}/>{resource!=="announcements"?<Input className="max-w-md" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Cari..." aria-label={`Cari ${labels[resource]}`}/>:null}<State loading={q.isLoading} error={q.error} retry={()=>void q.refetch()}/>{!q.isLoading&&!q.error?(resource==="assignments"?<AssignmentCards rows={q.data?.records??[]}/>:<StudentCards rows={q.data?.records??[]} detailPath={detail} empty={`Belum ada ${labels[resource].toLowerCase()}.`}/>):null}</main>}
export function StudentAssignmentDetailPage(){const {assignmentId=""}=useParams();const q=useStudentDetail("assignments",assignmentId);const navigate=useNavigate();const record=q.data??{};const assignment=isRecord(record.assignment)?record.assignment:record;const canOpen=assignment.canOpen===true;return <main className="space-y-6"><PageHeader title={valueText(assignment.title)} description={valueText(assignment.instructions)}/><State loading={q.isLoading} error={q.error} retry={()=>void q.refetch()}/>{!q.isLoading&&!q.error?<Card><CardContent className="space-y-3 p-6"><p>Aktiviti: {valueText(isRecord(record.activity)?record.activity.title:"—")}</p><p>Tarikh akhir: {valueText(assignment.dueAt)}</p><p>Status: {valueText(isRecord(assignment.availability)?assignment.availability.status:"—")}</p><Button disabled={!canOpen} onClick={()=>navigate(`/murid/tugasan/${assignmentId}/mainkan`)}>{canOpen?"Mula atau sambung":"Tidak tersedia"}</Button></CardContent></Card>:null}</main>}
export function StudentPlayerPage(){const {assignmentId=""}=useParams();const q=useDelivery(assignmentId);const navigate=useNavigate();if(q.isLoading)return <LoadingSpinner label="Membuka tugasan..."/>;if(q.error)return <ActivityErrorState message="Tugasan tidak dapat dibuka. Sila semak status tugasan atau cuba lagi." onRetry={()=>void q.refetch()} onExit={()=>navigate(`/murid/tugasan/${assignmentId}`)}/>;const activity=isRecord(q.data?.activity)?q.data.activity:{};const attempt=isRecord(q.data?.attempt)?q.data.attempt:{};const items=Array.isArray(activity.items)?activity.items:[];if(!items.length)return <ActivityErrorState message="Kandungan aktiviti belum tersedia untuk dimainkan. Tugasan tidak dihantar." onRetry={()=>void q.refetch()} onExit={()=>navigate(`/murid/tugasan/${assignmentId}`)}/>;return <main className="space-y-4"><PageHeader title={valueText(activity.title)} description={`Percubaan ${valueText(attempt.attemptNumber)}`}/><p className="rounded-lg border border-border p-4 text-muted-foreground">Pemain aktiviti sedia ada memerlukan DTO item lengkap. Kontrak penghantaran semasa tidak menyediakan item.</p></main>}
export function StudentDetailPage({resource}:{resource:"submissions"|"assessments"}){const p=useParams();const id=p.submissionId??p.assessmentId??"";const q=useStudentDetail(resource,id);const post=useStudentPost();return <main className="space-y-6"><PageHeader title={labels[resource]}/><State loading={q.isLoading} error={q.error} retry={()=>void q.refetch()}/>{q.data?<Card><CardContent className="grid gap-3 p-6 sm:grid-cols-2">{safeEntries(q.data).map(([k,v])=><div key={k}><p className="text-xs uppercase text-muted-foreground">{k}</p><p>{typeof v==="object"&&v!==null?"Maklumat tersedia":valueText(v)}</p></div>)}</CardContent></Card>:null}{resource==="submissions"&&id?<Button disabled={post.isPending} onClick={()=>post.mutate({path:`/student/submissions/${id}/revise`})}>Mula pembetulan jika dibenarkan</Button>:null}</main>}
export function StudentProgressPage(){const q=useStudentDashboard();const analytics=isRecord(q.data?.analytics)?q.data.analytics:{};return <main className="space-y-6"><PageHeader title="Kemajuan Saya" description="Kemajuan Pembelajaran berdasarkan rekod yang selamat."/><State loading={q.isLoading} error={q.error} retry={()=>void q.refetch()}/>{!q.isLoading&&!q.error?<StudentStats items={[{label:"Kemajuan Pembelajaran",value:isRecord(analytics.mastery)?analytics.mastery.currentProgress:"—"},{label:"Trend",value:isRecord(analytics.mastery)?analytics.mastery.trend:"—"}]}/>:null}</main>}
