import { NotificationChannel, NotificationType, UserRole } from "@prisma/client";
import { prisma } from "../config/prisma.js";
import { AppError } from "../errors/app-error.js";
import type { AuthenticatedSession } from "../middleware/auth.middleware.js";
import { recordAuditEvent } from "./audit.service.js";
import { createNotification, type NotificationContext } from "./notification.service.js";
import { canPublishAnnouncement, notificationDenied, requireSchoolScope } from "./notification-policy.js";
import type { AnnouncementInput } from "../validators/notification.validator.js";
export interface AnnouncementContext extends NotificationContext {}
function dto(announcement: { id: string; title: string; body: string; priority: string; pinned: boolean; publishAt: Date | null; publishedAt: Date | null; expiresAt: Date | null; archivedAt: Date | null; createdAt: Date }) { return { id: announcement.id, title: announcement.title, body: announcement.body, priority: announcement.priority, pinned: announcement.pinned, publishAt: announcement.publishAt, publishedAt: announcement.publishedAt, expiresAt: announcement.expiresAt, archivedAt: announcement.archivedAt, createdAt: announcement.createdAt }; }
async function audit(context: AnnouncementContext, action: "ANNOUNCEMENT_PUBLISHED" | "ANNOUNCEMENT_ARCHIVED", id: string, schoolId: string | null): Promise<void> { await recordAuditEvent({ actorUserId: context.actor.userId, actorProfileId: context.actor.profileId, actorRole: context.actor.role, actorName: null, action, resourceType: "ANNOUNCEMENT", resourceId: id, schoolId, before: null, after: null, timestamp: new Date(), requestIp: context.requestIp ?? null, userAgent: context.userAgent ?? null }, { strict: false }); }
async function validateTargets(input: AnnouncementInput, actor: AuthenticatedSession): Promise<void> { if (!canPublishAnnouncement(actor)) throw notificationDenied(); if (actor.role === UserRole.ADMIN) { if (!actor.schoolId) throw notificationDenied(); if (input.schoolId && input.schoolId !== actor.schoolId) throw notificationDenied(); if (input.targets.some((target) => target.schoolId && target.schoolId !== actor.schoolId)) throw notificationDenied(); } if (actor.role === UserRole.TEACHER) { if (input.schoolId && input.schoolId !== actor.schoolId) throw notificationDenied(); if (input.targets.some((target) => !target.classId || (target.schoolId && target.schoolId !== actor.schoolId))) throw notificationDenied(); const classes = await prisma.schoolClass.count({ where: { id: { in: input.targets.map((target) => target.classId ?? "") }, teacherId: actor.profileId, schoolId: actor.schoolId ?? undefined } }); if (classes !== input.targets.length) throw notificationDenied(); } }
export async function createAnnouncement(input: AnnouncementInput, context: AnnouncementContext) { await validateTargets(input, context.actor); const targets = input.targets.map((target) => ({ ...target, schoolId: target.schoolId ?? (context.actor.role === UserRole.SUPER_ADMIN || target.classId ? undefined : context.actor.schoolId ?? undefined) })); const announcement = await prisma.announcement.create({ data: { title: input.title, body: input.body, imageUrl: input.imageUrl ?? null, attachmentUrl: input.attachmentUrl ?? null, priority: input.priority, pinned: input.pinned, schoolId: input.schoolId ?? (context.actor.role === UserRole.SUPER_ADMIN ? null : context.actor.schoolId), createdByUserId: context.actor.userId, publishAt: input.publishAt ?? null, expiresAt: input.expiresAt ?? null, targets: { create: targets } }, include: { targets: true } }); return { ...dto(announcement), targets: announcement.targets.map((target) => ({ schoolId: target.schoolId, classId: target.classId, role: target.role })) }; }
async function targetUsers(announcementId: string) { const targets = await prisma.announcementTarget.findMany({ where: { announcementId }, include: { schoolClass: { select: { students: { select: { userId: true } } } } } }); const ids = new Set<string>(); for (const target of targets) { if (target.classId && target.schoolClass) target.schoolClass.students.forEach((student) => ids.add(student.userId)); else { const users = await prisma.user.findMany({ where: { ...(target.role ? { role: target.role } : {}), ...(target.schoolId ? { OR: [{ admin: { schoolId: target.schoolId } }, { teacher: { schoolId: target.schoolId } }, { student: { schoolId: target.schoolId } }, { parent: { students: { some: { student: { schoolId: target.schoolId } } } } }] } : {}) }, select: { id: true } }); users.forEach((user) => ids.add(user.id)); } } return [...ids]; }
export async function publishAnnouncement(id: string, context: AnnouncementContext) { const announcement = await prisma.announcement.findUnique({ where: { id }, include: { targets: true } }); if (!announcement || announcement.archivedAt) throw new AppError("ANNOUNCEMENT_NOT_FOUND", 404, "Pengumuman tidak ditemui."); if (context.actor.role === UserRole.TEACHER && announcement.createdByUserId !== context.actor.userId) throw notificationDenied(); if (context.actor.role !== UserRole.TEACHER) requireSchoolScope(context.actor, announcement.schoolId); const users = await targetUsers(id); const publishedAt = new Date(); await prisma.announcement.update({ where: { id }, data: { publishedAt } }); await createNotification({ type: NotificationType.ANNOUNCEMENT, channel: NotificationChannel.BOTH, priority: announcement.priority, title: announcement.title, body: announcement.body, imageUrl: announcement.imageUrl, attachmentUrl: announcement.attachmentUrl, schoolId: announcement.schoolId, recipientUserIds: users, scheduledFor: announcement.publishAt && announcement.publishAt > publishedAt ? announcement.publishAt : null, expiresAt: announcement.expiresAt, sourceType: "ANNOUNCEMENT", sourceId: announcement.id }, context); await audit(context, "ANNOUNCEMENT_PUBLISHED", id, announcement.schoolId); return { id, publishedAt, recipientCount: users.length }; }
export async function listAnnouncements(context: AnnouncementContext) { const now = new Date(); const records = await prisma.announcement.findMany({ where: { archivedAt: null, OR: [{ schoolId: null }, { schoolId: context.actor.schoolId }], AND: [{ OR: [{ publishedAt: null }, { publishedAt: { lte: now } }] }, { OR: [{ expiresAt: null }, { expiresAt: { gt: now } }] }] }, orderBy: [{ pinned: "desc" }, { publishedAt: "desc" }] }); return { announcements: records.map(dto) }; }
export async function archiveAnnouncement(id: string, context: AnnouncementContext) { const announcement = await prisma.announcement.findUnique({ where: { id } }); if (!announcement) throw new AppError("ANNOUNCEMENT_NOT_FOUND", 404, "Pengumuman tidak ditemui."); if (context.actor.role === UserRole.TEACHER && announcement.createdByUserId !== context.actor.userId) throw notificationDenied(); if (context.actor.role !== UserRole.TEACHER) requireSchoolScope(context.actor, announcement.schoolId); await prisma.announcement.update({ where: { id }, data: { archivedAt: new Date() } }); await audit(context, "ANNOUNCEMENT_ARCHIVED", id, announcement.schoolId); return { id, archived: true }; }
