import { NotificationChannel, NotificationPriority, NotificationStatus, NotificationType, Prisma, UserRole } from "@prisma/client";
import { prisma } from "../config/prisma.js";
import { AppError } from "../errors/app-error.js";
import type { AuthenticatedSession } from "../middleware/auth.middleware.js";
import { recordAuditEvent } from "./audit.service.js";
import { notificationEmailTemplate, sendResendEmail } from "./notification-email.service.js";
import { notificationDenied } from "./notification-policy.js";
import type { NotificationQuery, PreferencesInput } from "../validators/notification.validator.js";

export interface NotificationContext { actor: AuthenticatedSession; requestIp?: string | null; userAgent?: string | null; }
export interface CreateNotificationInput { type: NotificationType; channel?: NotificationChannel; priority?: NotificationPriority; title: string; body: string; schoolId?: string | null; recipientUserIds: string[]; deepLink?: string | null; imageUrl?: string | null; attachmentUrl?: string | null; scheduledFor?: Date | null; expiresAt?: Date | null; sourceType?: string | null; sourceId?: string | null; metadata?: Prisma.InputJsonValue; }
const preferenceKey: Record<NotificationType, keyof Pick<PreferencesInput, "assignments" | "assessments" | "announcements" | "ai" | "parentProgress" | "reminders" | "security"> | null> = { SYSTEM: null, ANNOUNCEMENT: "announcements", ASSIGNMENT: "assignments", SUBMISSION: "assignments", ASSESSMENT: "assessments", PBD_PROGRESS: "parentProgress", PARENT_PROGRESS: "parentProgress", TEACHER_REVIEW: "assignments", REVISION_REQUIRED: "assignments", AI_COMPLETED: "ai", REMINDER: "reminders", SECURITY: "security", PROFILE: null, ACCOUNT: null };
function error(code: string, status: number, message: string): AppError { return new AppError(code, status, message); }
function dto(recipient: { id: string; status: NotificationStatus; readAt: Date | null; archivedAt: Date | null; createdAt: Date; notification: { id: string; type: NotificationType; channel: NotificationChannel; priority: NotificationPriority; title: string; body: string; imageUrl: string | null; attachmentUrl: string | null; deepLink: string | null; expiresAt: Date | null; createdAt: Date } }) { const n = recipient.notification; return { id: n.id, type: n.type, channel: n.channel, priority: n.priority, title: n.title, body: n.body, imageUrl: n.imageUrl, attachmentUrl: n.attachmentUrl, deepLink: n.deepLink, status: recipient.status, readAt: recipient.readAt, archivedAt: recipient.archivedAt, expiresAt: n.expiresAt, createdAt: n.createdAt }; }
async function audit(context: NotificationContext, action: "NOTIFICATION_CREATED" | "NOTIFICATION_DELIVERED" | "NOTIFICATION_FAILED" | "NOTIFICATION_READ" | "NOTIFICATION_ARCHIVED" | "NOTIFICATION_PREFERENCE_CHANGED", resourceId: string, schoolId: string | null, metadata: Record<string, string | number | boolean | null>): Promise<void> { await recordAuditEvent({ actorUserId: context.actor.userId, actorProfileId: context.actor.profileId, actorRole: context.actor.role, actorName: null, action, resourceType: "NOTIFICATION", resourceId, schoolId, before: null, after: null, metadata, timestamp: new Date(), requestIp: context.requestIp ?? null, userAgent: context.userAgent ?? null }, { strict: false }); }
export async function createNotification(input: CreateNotificationInput, context: NotificationContext): Promise<{ id: string; recipientCount: number }> {
  if (!input.recipientUserIds.length) throw error("NOTIFICATION_RECIPIENT_REQUIRED", 400, "Penerima notifikasi diperlukan.");
  if (input.expiresAt && input.scheduledFor && input.expiresAt <= input.scheduledFor) throw error("NOTIFICATION_EXPIRY_INVALID", 400, "Tarikh tamat mesti selepas jadual penghantaran.");
  const recipients = [...new Set(input.recipientUserIds)];
  const users = await prisma.user.findMany({ where: { id: { in: recipients }, accountStatus: "ACTIVE" }, select: { id: true, email: true, notificationPreferences: true } });
  const allowed = users.filter((user) => { const key = preferenceKey[input.type]; return !key || user.notificationPreferences?.[key] !== false; });
  const notification = await prisma.notification.create({ data: { type: input.type, channel: input.channel ?? NotificationChannel.IN_APP, priority: input.priority ?? NotificationPriority.NORMAL, title: input.title.trim(), body: input.body.trim(), schoolId: input.schoolId ?? null, createdByUserId: context.actor.userId, deepLink: input.deepLink ?? null, imageUrl: input.imageUrl ?? null, attachmentUrl: input.attachmentUrl ?? null, scheduledFor: input.scheduledFor ?? null, expiresAt: input.expiresAt ?? null, sourceType: input.sourceType ?? null, sourceId: input.sourceId ?? null, metadata: input.metadata, status: input.scheduledFor && input.scheduledFor > new Date() ? NotificationStatus.PENDING : NotificationStatus.QUEUED, recipients: { create: allowed.map((user) => ({ userId: user.id, status: input.scheduledFor && input.scheduledFor > new Date() ? NotificationStatus.PENDING : NotificationStatus.QUEUED })) } }, include: { recipients: true } });
  await audit(context, "NOTIFICATION_CREATED", notification.id, notification.schoolId, { type: notification.type, recipientCount: allowed.length });
  return { id: notification.id, recipientCount: allowed.length };
}
export async function listNotifications(query: NotificationQuery, context: NotificationContext, unreadOnly = false) {
  const where: Prisma.NotificationRecipientWhereInput = { userId: context.actor.userId, deletedAt: null, notification: { deletedAt: null, ...(query.type ? { type: query.type } : {}), ...(query.priority ? { priority: query.priority } : {}), ...(query.search ? { OR: [{ title: { contains: query.search, mode: "insensitive" } }, { body: { contains: query.search, mode: "insensitive" } }] } : {}), OR: [{ expiresAt: null }, { expiresAt: { gt: new Date() } }] }, ...(unreadOnly || query.status === "unread" ? { readAt: null, archivedAt: null } : {}), ...(query.status === "read" ? { readAt: { not: null }, archivedAt: null } : {}), ...(query.status === "archived" ? { archivedAt: { not: null } } : {}) };
  const [rows, total, unread] = await Promise.all([prisma.notificationRecipient.findMany({ where, include: { notification: true }, orderBy: { createdAt: query.sortOrder }, skip: (query.page - 1) * query.limit, take: query.limit }), prisma.notificationRecipient.count({ where }), prisma.notificationRecipient.count({ where: { userId: context.actor.userId, readAt: null, archivedAt: null, deletedAt: null, notification: { deletedAt: null } } })]);
  return { notifications: rows.map(dto), unreadCount: unread, pagination: { page: query.page, limit: query.limit, total, totalPages: Math.ceil(total / query.limit) } };
}
async function ownRecipient(notificationId: string, context: NotificationContext) { const recipient = await prisma.notificationRecipient.findFirst({ where: { notificationId, userId: context.actor.userId, deletedAt: null }, include: { notification: true } }); if (!recipient || recipient.notification.deletedAt) throw error("NOTIFICATION_NOT_FOUND", 404, "Notifikasi tidak ditemui."); return recipient; }
export async function getNotification(id: string, context: NotificationContext) { return dto(await ownRecipient(id, context)); }
export async function markRead(ids: string[], context: NotificationContext) { const owned = await prisma.notificationRecipient.findMany({ where: { notificationId: { in: ids }, userId: context.actor.userId, deletedAt: null }, select: { id: true, notificationId: true, notification: { select: { schoolId: true } } } }); const now = new Date(); await prisma.notificationRecipient.updateMany({ where: { id: { in: owned.map((entry) => entry.id) }, readAt: null }, data: { readAt: now, status: NotificationStatus.READ } }); await Promise.all(owned.map((entry) => audit(context, "NOTIFICATION_READ", entry.notificationId, entry.notification.schoolId, {}))); return { updated: owned.length }; }
export async function markAllRead(context: NotificationContext) { const result = await prisma.notificationRecipient.updateMany({ where: { userId: context.actor.userId, readAt: null, archivedAt: null, deletedAt: null }, data: { readAt: new Date(), status: NotificationStatus.READ } }); return { updated: result.count }; }
export async function archiveNotifications(ids: string[], context: NotificationContext) { const rows = await prisma.notificationRecipient.findMany({ where: { notificationId: { in: ids }, userId: context.actor.userId, deletedAt: null }, select: { id: true, notificationId: true, notification: { select: { schoolId: true } } } }); await prisma.notificationRecipient.updateMany({ where: { id: { in: rows.map((row) => row.id) } }, data: { archivedAt: new Date(), status: NotificationStatus.ARCHIVED } }); await Promise.all(rows.map((row) => audit(context, "NOTIFICATION_ARCHIVED", row.notificationId, row.notification.schoolId, {}))); return { updated: rows.length }; }
export async function deleteNotification(id: string, context: NotificationContext) { const recipient = await ownRecipient(id, context); await prisma.notificationRecipient.update({ where: { id: recipient.id }, data: { deletedAt: new Date() } }); return { id, deleted: true }; }
export async function preferences(context: NotificationContext) { return prisma.notificationPreference.upsert({ where: { userId: context.actor.userId }, create: { userId: context.actor.userId }, update: {} }); }
export async function updatePreferences(input: PreferencesInput, context: NotificationContext) { const result = await prisma.notificationPreference.upsert({ where: { userId: context.actor.userId }, create: { userId: context.actor.userId, ...input }, update: input }); await audit(context, "NOTIFICATION_PREFERENCE_CHANGED", result.id, context.actor.schoolId, { changed: Object.keys(input).length }); return result; }
export async function deliverPendingNotifications(systemContext: NotificationContext): Promise<{ delivered: number; failed: number }> { const now = new Date(); const rows = await prisma.notificationRecipient.findMany({ where: { status: { in: [NotificationStatus.PENDING, NotificationStatus.QUEUED] }, notification: { deletedAt: null, AND: [{ OR: [{ scheduledFor: null }, { scheduledFor: { lte: now } }] }, { OR: [{ expiresAt: null }, { expiresAt: { gt: now } }] }] } }, include: { notification: true, user: { select: { email: true, notificationPreferences: true } } }, take: 200 }); let delivered = 0; let failed = 0; for (const row of rows) { const n = row.notification; const inApp = (n.channel === NotificationChannel.IN_APP || n.channel === NotificationChannel.BOTH) && row.user.notificationPreferences?.inAppEnabled !== false; const wantsEmail = (n.channel === NotificationChannel.EMAIL || n.channel === NotificationChannel.BOTH) && row.user.notificationPreferences?.emailEnabled !== false && Boolean(row.user.email); try { if (wantsEmail && row.user.email) { const sent = await sendResendEmail({ to: row.user.email, subject: n.title, html: notificationEmailTemplate(n) }); await prisma.notificationDelivery.create({ data: { notificationId: n.id, recipientId: row.id, channel: NotificationChannel.EMAIL, status: NotificationStatus.SENT, provider: sent.provider, providerId: sent.providerId, attemptedAt: now, deliveredAt: now } }); }
      if (inApp) await prisma.notificationDelivery.create({ data: { notificationId: n.id, recipientId: row.id, channel: NotificationChannel.IN_APP, status: NotificationStatus.SENT, provider: "IN_APP", attemptedAt: now, deliveredAt: now } });
      await prisma.notificationRecipient.update({ where: { id: row.id }, data: { status: NotificationStatus.SENT } }); await audit(systemContext, "NOTIFICATION_DELIVERED", n.id, n.schoolId, { recipientId: row.id }); delivered++;
    } catch (caught) { const reason = caught instanceof Error ? caught.message.slice(0, 500) : "DELIVERY_FAILED"; await prisma.notificationDelivery.create({ data: { notificationId: n.id, recipientId: row.id, channel: n.channel, status: NotificationStatus.FAILED, attemptedAt: now, failedAt: now, retryCount: 1, nextRetryAt: new Date(now.getTime() + 5 * 60_000), failureReason: reason } }); await prisma.notificationRecipient.update({ where: { id: row.id }, data: { status: NotificationStatus.FAILED } }); await audit(systemContext, "NOTIFICATION_FAILED", n.id, n.schoolId, { reason }); failed++; }
  } return { delivered, failed }; }
export async function notifyAssignmentPublished(assignmentId: string, context: NotificationContext) { const assignment = await prisma.assignment.findUnique({ where: { id: assignmentId }, include: { studentTargets: { include: { student: { select: { userId: true } } } }, classTargets: { include: { schoolClass: { include: { students: { select: { userId: true } } } } } } } }); if (!assignment) return null; const userIds = [...new Set([...assignment.studentTargets.map((target) => target.student.userId), ...assignment.classTargets.flatMap((target) => target.schoolClass.students.map((student) => student.userId))])]; return createNotification({ type: NotificationType.ASSIGNMENT, title: "Tugasan baharu", body: assignment.title, schoolId: assignment.schoolId, recipientUserIds: userIds, deepLink: `/assignments/${assignment.id}`, sourceType: "ASSIGNMENT", sourceId: assignment.id, priority: assignment.priority === "HIGH" ? NotificationPriority.HIGH : NotificationPriority.NORMAL }, context); }
export async function notifySubmissionEvent(submissionId: string, reviewed: boolean, revisionRequired: boolean, context: NotificationContext) { const submission = await prisma.submission.findUnique({ where: { id: submissionId }, include: { student: { include: { parents: { include: { parent: { select: { userId: true } } } } } }, assignment: { include: { assignedByTeacher: { select: { userId: true } } } } } }); if (!submission) return null; const recipientUserIds = reviewed ? [submission.student.userId, ...submission.student.parents.map((link) => link.parent.userId)] : [submission.assignment.assignedByTeacher.userId]; return createNotification({ type: revisionRequired ? NotificationType.REVISION_REQUIRED : reviewed ? NotificationType.TEACHER_REVIEW : NotificationType.SUBMISSION, title: revisionRequired ? "Pembetulan diperlukan" : reviewed ? "Semakan tugasan tersedia" : "Penyerahan baharu diterima", body: submission.assignment.title, schoolId: submission.schoolId, recipientUserIds, deepLink: `/submissions/${submission.id}`, sourceType: "SUBMISSION", sourceId: submission.id }, context); }
export async function notifyAssessmentEvent(assessmentId: string, context: NotificationContext) { const assessment = await prisma.assessment.findUnique({ where: { id: assessmentId }, include: { student: { include: { parents: { include: { parent: { select: { userId: true } } } } } }, assignment: { select: { title: true } } } }); if (!assessment) return null; return createNotification({ type: NotificationType.ASSESSMENT, title: "Pentaksiran tersedia", body: assessment.assignment.title, schoolId: assessment.schoolId, recipientUserIds: [assessment.student.userId, ...assessment.student.parents.map((link) => link.parent.userId)], deepLink: `/assessments/${assessment.id}`, sourceType: "ASSESSMENT", sourceId: assessment.id }, context); }
export async function notifyPbdMasteryChanged(studentId: string, context: NotificationContext) { const student = await prisma.student.findUnique({ where: { id: studentId }, include: { parents: { include: { parent: { select: { userId: true } } } }, class: { include: { teacher: { select: { userId: true } } } } } }); if (!student) return null; return createNotification({ type: NotificationType.PBD_PROGRESS, title: "Kemajuan penguasaan dikemaskini", body: student.fullName, schoolId: student.schoolId, recipientUserIds: [student.class.teacher.userId, ...student.parents.map((link) => link.parent.userId)], deepLink: `/pbd/students/${student.id}`, sourceType: "PBD_MASTERY", sourceId: student.id }, context); }
export async function notifyAiCompleted(userId: string, schoolId: string | null, sourceId: string, title: string, context: NotificationContext) { return createNotification({ type: NotificationType.AI_COMPLETED, title, body: "Draf AI sedia untuk semakan.", schoolId, recipientUserIds: [userId], deepLink: `/ai/outputs/${sourceId}`, sourceType: "AI", sourceId }, context); }
export async function notifySecurityEvent(userId: string, title: string, body: string, context: NotificationContext) { return createNotification({ type: NotificationType.SECURITY, channel: NotificationChannel.BOTH, priority: NotificationPriority.HIGH, title, body, schoolId: context.actor.schoolId, recipientUserIds: [userId], sourceType: "SECURITY", sourceId: userId }, context); }
export { notificationDenied };
