import { MasteryLevel, Prisma, UserRole } from "@prisma/client";
import { prisma } from "../config/prisma.js";
import { AppError } from "../errors/app-error.js";
import type { ListEvidenceQuery, ListMasteryQuery } from "../validators/pbd.validator.js";
import { MASTERY_POLICY } from "./mastery-policy.js";
import { requireStudentPbdAccess, type PbdContext } from "./mastery.service.js";

const error = (code: string, status: number, message: string) => new AppError(code, status, message);
const pageInfo = (page: number, limit: number, total: number) => ({ page, limit, total, totalPages: Math.ceil(total / limit), hasNextPage: page * limit < total, hasPreviousPage: page > 1 });
const number = (value: Prisma.Decimal | null) => value?.toNumber() ?? null;
const evidenceInclude = { student: { include: { class: { select: { id: true, className: true } } } }, remedialSkill: { select: { id: true, code: true, name: true } }, learningStandard: { select: { id: true, code: true, description: true } } } satisfies Prisma.PBDEvidenceInclude;
const masteryInclude = { student: { include: { class: { select: { id: true, className: true } } } }, remedialSkill: { select: { id: true, code: true, name: true, languageStructureId: true } }, learningStandard: { select: { id: true, code: true, description: true } } } satisfies Prisma.StudentMasteryInclude;
function evidenceDto(record: Prisma.PBDEvidenceGetPayload<{ include: typeof evidenceInclude }>) { return { id: record.id, student: { id: record.student.id, studentId: record.student.studentId, name: record.student.fullName, class: { id: record.student.class.id, name: record.student.class.className } }, curriculum: { versionId: record.curriculumVersionId, programmeId: record.programmeId, remedialSkill: record.remedialSkill, learningStandard: record.learningStandard }, type: record.evidenceType, strength: record.strength, percentage: number(record.percentage), observedLevel: record.observedLevel, summary: record.summary, observedAt: record.observedAt, isValid: record.isValid }; }
function masteryDto(record: Prisma.StudentMasteryGetPayload<{ include: typeof masteryInclude }>) { return { id: record.id, student: { id: record.student.id, studentId: record.student.studentId, name: record.student.fullName, class: { id: record.student.class.id, name: record.student.class.className } }, curriculum: { remedialSkill: { id: record.remedialSkill.id, code: record.remedialSkill.code, name: record.remedialSkill.name }, learningStandard: record.learningStandard }, mastery: { currentLevel: record.currentLevel, status: record.status, decisionSource: record.decisionSource, recommendedLevel: record.recommendedLevel, recommendedConfidence: number(record.recommendedConfidence), evidenceCount: record.evidenceCount, activityCount: record.activityCount, trend: record.trend, latestEvidenceAt: record.latestEvidenceAt, confirmedAt: record.confirmedAt } }; }
function managementScope(context: PbdContext): Prisma.StudentWhereInput {
  if (context.actor.role === UserRole.SUPER_ADMIN) return {};
  if (context.actor.role === UserRole.ADMIN) return context.actor.schoolId ? { schoolId: context.actor.schoolId } : {};
  if (context.actor.role === UserRole.TEACHER) return { schoolId: context.actor.schoolId ?? undefined, class: { teacherId: context.actor.profileId } };
  throw error("PBD_EVIDENCE_ACCESS_DENIED", 403, "Anda tidak dibenarkan mengakses PBD.");
}
export async function listEvidence(query: ListEvidenceQuery, context: PbdContext) { const where: Prisma.PBDEvidenceWhereInput = { student: managementScope(context), ...(query.studentId ? { studentId: query.studentId } : {}), ...(query.schoolId ? { schoolId: query.schoolId } : {}), ...(query.classId ? { student: { ...managementScope(context), classId: query.classId } } : {}), ...(query.curriculumVersionId ? { curriculumVersionId: query.curriculumVersionId } : {}), ...(query.programmeId ? { programmeId: query.programmeId } : {}), ...(query.remedialSkillId ? { remedialSkillId: query.remedialSkillId } : {}), ...(query.learningStandardId ? { learningStandardId: query.learningStandardId } : {}), ...(query.evidenceType ? { evidenceType: query.evidenceType } : {}), ...(query.strength ? { strength: query.strength } : {}), ...(query.isValid !== undefined ? { isValid: query.isValid } : {}), ...(query.observedFrom || query.observedTo ? { observedAt: { ...(query.observedFrom ? { gte: query.observedFrom } : {}), ...(query.observedTo ? { lte: query.observedTo } : {}) } } : {}), ...(query.search ? { student: { ...managementScope(context), OR: [{ fullName: { contains: query.search, mode: "insensitive" } }, { studentId: { contains: query.search, mode: "insensitive" } }] } } : {}) }; const [records, total] = await Promise.all([prisma.pBDEvidence.findMany({ where, include: evidenceInclude, orderBy: { [query.sortBy]: query.sortOrder }, skip: (query.page - 1) * query.limit, take: query.limit }), prisma.pBDEvidence.count({ where })]); return { evidence: records.map(evidenceDto), pagination: pageInfo(query.page, query.limit, total) }; }
export async function getEvidence(id: string, context: PbdContext) { const record = await prisma.pBDEvidence.findUnique({ where: { id }, include: evidenceInclude }); if (!record) throw error("PBD_EVIDENCE_NOT_FOUND", 404, "Rekod bukti PBD tidak ditemui."); await requireStudentPbdAccess(record.studentId, context); return evidenceDto(record); }
export async function listMastery(query: ListMasteryQuery, context: PbdContext) { const where: Prisma.StudentMasteryWhereInput = { student: managementScope(context), ...(query.studentId ? { studentId: query.studentId } : {}), ...(query.schoolId ? { schoolId: query.schoolId } : {}), ...(query.classId ? { student: { ...managementScope(context), classId: query.classId } } : {}), ...(query.curriculumVersionId ? { curriculumVersionId: query.curriculumVersionId } : {}), ...(query.programmeId ? { programmeId: query.programmeId } : {}), ...(query.remedialSkillId ? { remedialSkillId: query.remedialSkillId } : {}), ...(query.learningStandardId ? { learningStandardId: query.learningStandardId } : {}), ...(query.currentLevel ? { currentLevel: query.currentLevel } : {}), ...(query.recommendedLevel ? { recommendedLevel: query.recommendedLevel } : {}), ...(query.status ? { status: query.status } : {}), ...(query.trend ? { trend: query.trend } : {}), ...(query.updatedFrom || query.updatedTo ? { updatedAt: { ...(query.updatedFrom ? { gte: query.updatedFrom } : {}), ...(query.updatedTo ? { lte: query.updatedTo } : {}) } } : {}), ...(query.search ? { student: { ...managementScope(context), OR: [{ fullName: { contains: query.search, mode: "insensitive" } }, { studentId: { contains: query.search, mode: "insensitive" } }] } } : {}) }; const [records, total] = await Promise.all([prisma.studentMastery.findMany({ where, include: masteryInclude, orderBy: { [query.sortBy]: query.sortOrder }, skip: (query.page - 1) * query.limit, take: query.limit }), prisma.studentMastery.count({ where })]); return { mastery: records.map(masteryDto), pagination: pageInfo(query.page, query.limit, total) }; }
export async function getMastery(id: string, context: PbdContext) { const record = await prisma.studentMastery.findUnique({ where: { id }, include: { ...masteryInclude, history: { orderBy: { createdAt: "desc" }, select: { previousLevel: true, newLevel: true, previousStatus: true, newStatus: true, decisionSource: true, evidenceCount: true, reason: true, createdAt: true } } } }); if (!record) throw error("PBD_MASTERY_NOT_FOUND", 404, "Rekod penguasaan tidak ditemui."); await requireStudentPbdAccess(record.studentId, context); return { ...masteryDto(record), history: record.history }; }
async function ownedStudent(context: PbdContext) { if (context.actor.role !== UserRole.STUDENT) throw error("PBD_PROGRESS_NOT_AVAILABLE", 403, "Kemajuan tidak tersedia."); const student = await prisma.student.findUnique({ where: { userId: context.actor.userId } }); if (!student) throw error("PBD_PROGRESS_NOT_AVAILABLE", 404, "Data kemajuan murid tidak tersedia."); return student; }
async function progress(studentId: string) { const masteries = await prisma.studentMastery.findMany({ where: { studentId, archivedAt: null, curriculumVersion: { status: "PUBLISHED" } }, include: { programme: { select: { id: true, name: true } }, remedialSkill: { include: { languageStructure: { select: { id: true, code: true, name: true, sequence: true } } } } }, orderBy: { remedialSkill: { sequence: "asc" } } }); const programme = masteries[0]?.programme ?? null; const levelCount = Object.fromEntries(Object.values(MasteryLevel).map((level) => [level, 0])) as Record<MasteryLevel, number>; for (const mastery of masteries) levelCount[mastery.currentLevel] += 1; const total = masteries.length; const overall = total === 0 ? 0 : Math.round(masteries.reduce((sum, mastery) => sum + MASTERY_POLICY.levelWeights[mastery.currentLevel], 0) / total); const structures = new Map<string, { id: string; code: string; name: string; sequence: number; skills: typeof masteries }>(); for (const mastery of masteries) { const structure = mastery.remedialSkill.languageStructure; const group = structures.get(structure.id) ?? { ...structure, skills: [] as unknown as typeof masteries }; group.skills.push(mastery); structures.set(structure.id, group); } return { programme, summary: { totalSkills: total, notStarted: levelCount.NOT_STARTED, emerging: levelCount.EMERGING, developing: levelCount.DEVELOPING, achieved: levelCount.ACHIEVED, mastered: levelCount.MASTERED, overallProgressPercentage: overall }, structures: [...structures.values()].sort((a, b) => a.sequence - b.sequence).map((group) => ({ id: group.id, code: group.code, name: group.name, progressPercentage: group.skills.length === 0 ? 0 : Math.round(group.skills.reduce((sum, mastery) => sum + MASTERY_POLICY.levelWeights[mastery.currentLevel], 0) / group.skills.length), skills: group.skills.map((mastery) => ({ id: mastery.remedialSkill.id, code: mastery.remedialSkill.code, name: mastery.remedialSkill.name, currentLevel: mastery.currentLevel, trend: mastery.trend, latestEvidenceAt: mastery.latestEvidenceAt, teacherFeedback: null })) })) }; }
export async function studentProgress(context: PbdContext) { return progress((await ownedStudent(context)).id); }
export async function studentSkillProgress(skillId: string, context: PbdContext) { const data = await studentProgress(context); const skill = data.structures.flatMap((structure) => structure.skills).find((entry) => entry.id === skillId); if (!skill) throw error("PBD_PROGRESS_NOT_AVAILABLE", 404, "Kemajuan kemahiran tidak tersedia."); return skill; }
async function parentStudent(studentId: string, context: PbdContext) { if (context.actor.role !== UserRole.PARENT) throw error("PBD_EVIDENCE_ACCESS_DENIED", 403, "Anda tidak dibenarkan mengakses kemajuan ini."); const parent = await prisma.parent.findUnique({ where: { userId: context.actor.userId } }); const link = parent ? await prisma.parentStudent.findUnique({ where: { parentId_studentId: { parentId: parent.id, studentId } } }) : null; if (!link) throw error("PBD_EVIDENCE_ACCESS_DENIED", 403, "Anda tidak dibenarkan mengakses kemajuan murid ini."); }
export async function parentProgress(studentId: string, context: PbdContext) { await parentStudent(studentId, context); return progress(studentId); }
export async function parentSkillProgress(studentId: string, skillId: string, context: PbdContext) { const data = await parentProgress(studentId, context); const skill = data.structures.flatMap((structure) => structure.skills).find((entry) => entry.id === skillId); if (!skill) throw error("PBD_PROGRESS_NOT_AVAILABLE", 404, "Kemajuan kemahiran tidak tersedia."); return skill; }
export async function classProgress(classId: string, context: PbdContext) { if (context.actor.role !== UserRole.TEACHER && context.actor.role !== UserRole.SUPER_ADMIN && context.actor.role !== UserRole.ADMIN) throw error("PBD_MASTERY_ACCESS_DENIED", 403, "Anda tidak dibenarkan mengakses kelas ini."); const schoolClass = await prisma.schoolClass.findUnique({ where: { id: classId }, include: { students: { select: { id: true, fullName: true, studentId: true } } } }); if (!schoolClass || (context.actor.role === UserRole.TEACHER && (schoolClass.teacherId !== context.actor.profileId || schoolClass.schoolId !== context.actor.schoolId))) throw error("PBD_MASTERY_ACCESS_DENIED", 403, "Anda tidak dibenarkan mengakses kelas ini."); const masteries = await prisma.studentMastery.findMany({ where: { student: { classId }, archivedAt: null }, select: { studentId: true, remedialSkillId: true, currentLevel: true, trend: true, latestEvidenceAt: true } }); const distribution = Object.fromEntries(Object.values(MasteryLevel).map((level) => [level, 0])) as Record<MasteryLevel, number>; for (const mastery of masteries) distribution[mastery.currentLevel] += 1; const support = schoolClass.students.filter((student) => { const entries = masteries.filter((mastery) => mastery.studentId === student.id); return entries.length === 0 || entries.some((entry) => entry.currentLevel === MasteryLevel.NOT_STARTED || entry.currentLevel === MasteryLevel.EMERGING || entry.trend === "DECLINING"); }).map((student) => ({ id: student.id, studentId: student.studentId, name: student.fullName, status: "Memerlukan sokongan" })); return { class: { id: schoolClass.id, name: schoolClass.className }, studentCount: schoolClass.students.length, masteryDistribution: distribution, studentsRequiringSupport: support, skillCount: new Set(masteries.map((mastery) => mastery.remedialSkillId)).size }; }
