import type { ActivityCompletionSummary, ActivityMedia } from "../../types"
import type { CopyWritingActivityItem, CopyWritingCompletion, CopyWritingContentMode, CopyWritingHintType, CopyWritingLayout, CopyWritingMapResult, CopyWritingQuestion, CopyWritingReferenceDisplay, CopyWritingSessionState, CopyWritingSettings, CopyWritingState, CopyWritingStroke, CopyWritingSyllableUnit, CopyWritingTools } from "./copy-writing.types"

const MAX_REPETITIONS = 10
const UNSAFE_TEXT = /(?:<\s*\/?\s*[a-z][^>]*>|\b(?:javascript|vbscript|data)\s*:|\bscript\b|\bon[a-z]+\s*=)/iu

function asRecord(value: unknown): Record<string, unknown> | null { return value !== null && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : null }
function isContentMode(value: unknown): value is CopyWritingContentMode { return value === "LETTER" || value === "SYLLABLE" || value === "WORD" || value === "PHRASE" || value === "SENTENCE" }
function isHint(value: unknown): value is CopyWritingHintType { return value === "NONE" || value === "SHOW_REFERENCE" || value === "EMPHASIZE_FIRST_CHARACTER" || value === "PLAY_REFERENCE_AUDIO" || value === "SHOW_WRITING_LINES" }

function mapMedia(value: unknown, role: string): ActivityMedia[] | null {
  if (!Array.isArray(value)) return null
  const output: ActivityMedia[] = []
  for (const entry of value) {
    const media = asRecord(entry)
    if (!media || typeof media.key !== "string" || !media.key || (typeof media.url !== "string" && media.url !== null) || (typeof media.mimeType !== "string" && media.mimeType !== null) || (typeof media.altText !== "string" && media.altText !== null) || (typeof media.label !== "string" && media.label !== null)) return null
    output.push({ id: `copy-writing:${role}:${media.key}`, mediaKey: media.key, mediaRole: role, mimeType: media.mimeType, label: media.label, altText: media.altText, sequence: output.length, isPrimary: output.length === 0, url: media.url })
  }
  return output
}

function mapLayout(value: unknown): CopyWritingLayout | null {
  const layout = asRecord(value)
  if (!layout || (layout.lineStyle !== "NONE" && layout.lineStyle !== "BASELINE" && layout.lineStyle !== "TWO_LINE" && layout.lineStyle !== "THREE_LINE" && layout.lineStyle !== "FOUR_LINE") || typeof layout.lineCount !== "number" || !Number.isInteger(layout.lineCount) || typeof layout.lineSpacing !== "number" || !Number.isInteger(layout.lineSpacing) || typeof layout.showTopLine !== "boolean" || typeof layout.showMidline !== "boolean" || typeof layout.showBaseline !== "boolean" || typeof layout.showDescenderLine !== "boolean") return null
  return { lineStyle: layout.lineStyle, lineCount: layout.lineCount, lineSpacing: layout.lineSpacing, showTopLine: layout.showTopLine, showMidline: layout.showMidline, showBaseline: layout.showBaseline, showDescenderLine: layout.showDescenderLine }
}

function mapDisplay(value: unknown): CopyWritingReferenceDisplay | null {
  const display = asRecord(value)
  if (!display || (display.position !== "TOP" && display.position !== "LEFT" && display.position !== "ABOVE_EACH_LINE") || typeof display.fontSize !== "number" || !Number.isInteger(display.fontSize) || typeof display.showSyllableBreaks !== "boolean" || typeof display.syllableSeparator !== "string") return null
  return { position: display.position, fontSize: display.fontSize, showSyllableBreaks: display.showSyllableBreaks, syllableSeparator: display.syllableSeparator }
}

function mapSyllables(value: unknown, referenceText: string, required: boolean): CopyWritingSyllableUnit[] | null {
  if (!required) return (value === undefined || value === null || (Array.isArray(value) && value.length === 0)) ? [] : null
  if (!Array.isArray(value) || value.length === 0) return null
  const units = value.map((entry) => { const unit = asRecord(entry); return unit && typeof unit.id === "string" && typeof unit.value === "string" && typeof unit.sequence === "number" && Number.isInteger(unit.sequence) ? { id: unit.id, value: unit.value.normalize("NFC"), sequence: unit.sequence } : null })
  if (units.some((unit) => unit === null)) return null
  const valid = units.filter((unit): unit is CopyWritingSyllableUnit => unit !== null).sort((left, right) => left.sequence - right.sequence)
  return new Set(valid.map((unit) => unit.id)).size === valid.length && new Set(valid.map((unit) => unit.sequence)).size === valid.length && valid.every((unit, index) => unit.sequence === index + 1) && valid.map((unit) => unit.value).join("").normalize("NFC") === referenceText ? valid : null
}

function mapTools(value: unknown): CopyWritingTools | null { const tools = asRecord(value); if (!tools || tools.allowPen !== true || typeof tools.allowEraser !== "boolean" || typeof tools.allowUndo !== "boolean" || typeof tools.allowRedo !== "boolean" || typeof tools.allowClear !== "boolean" || typeof tools.allowStrokeWidthChange !== "boolean" || typeof tools.defaultStrokeWidth !== "number" || !Number.isInteger(tools.defaultStrokeWidth) || tools.defaultStrokeWidth < 2 || tools.defaultStrokeWidth > 20 || (tools.allowRedo === true && tools.allowUndo !== true)) return null; return { allowPen: true, allowEraser: tools.allowEraser, allowUndo: tools.allowUndo, allowRedo: tools.allowRedo, allowClear: tools.allowClear, allowStrokeWidthChange: tools.allowStrokeWidthChange, defaultStrokeWidth: tools.defaultStrokeWidth } }
function mapCompletion(value: unknown): CopyWritingCompletion | null { const completion = asRecord(value); if (!completion || typeof completion.minimumStrokeCount !== "number" || !Number.isInteger(completion.minimumStrokeCount) || completion.minimumStrokeCount < 1 || typeof completion.requireAllRepetitions !== "boolean" || (completion.minimumWritingRegionsUsed !== null && completion.minimumWritingRegionsUsed !== undefined && (typeof completion.minimumWritingRegionsUsed !== "number" || !Number.isInteger(completion.minimumWritingRegionsUsed)))) return null; return { minimumStrokeCount: completion.minimumStrokeCount, requireAllRepetitions: completion.requireAllRepetitions, minimumWritingRegionsUsed: typeof completion.minimumWritingRegionsUsed === "number" ? completion.minimumWritingRegionsUsed : null } }

export function mapCopyWritingQuestion(item: CopyWritingActivityItem): CopyWritingMapResult {
  const root = asRecord(item.configuration); const definition = root ? asRecord(root.copyWriting) : null
  const contentMode = definition?.contentMode; const layout = definition ? mapLayout(definition.writingLayout) : null; const display = definition ? mapDisplay(definition.referenceDisplay) : null; const tools = definition ? mapTools(definition.tools) : null; const completion = definition ? mapCompletion(definition.completion) : null; const hint = definition ? asRecord(definition.hint) : null
  if (!definition || !isContentMode(contentMode) || typeof definition.referenceText !== "string" || !definition.referenceText || UNSAFE_TEXT.test(definition.referenceText) || typeof definition.repetitionCount !== "number" || !Number.isInteger(definition.repetitionCount) || definition.repetitionCount < 1 || definition.repetitionCount > MAX_REPETITIONS || !layout || !display || !tools || !completion || !hint || !isHint(hint.type) || definition.writingDirection !== "LEFT_TO_RIGHT" || typeof definition.allowRetry !== "boolean" || typeof definition.clearOnRetry !== "boolean") return { ok: false, message: "Kontrak Menyalin yang lengkap tidak tersedia untuk item ini." }
  const canvas = asRecord(definition.canvas)
  if (!canvas || typeof canvas.width !== "number" || !Number.isInteger(canvas.width) || typeof canvas.height !== "number" || !Number.isInteger(canvas.height) || canvas.width < 400 || canvas.height < 200 || layout.lineCount < 1 || layout.lineSpacing < 24 || layout.lineCount * layout.lineSpacing > canvas.height || layout.lineCount > MAX_REPETITIONS || layout.lineCount < definition.repetitionCount && completion.requireAllRepetitions || display.fontSize < 24 || display.fontSize > 160) return { ok: false, message: "Kanvas atau susun atur tulisan item ini tidak sah." }
  const referenceText = definition.referenceText.normalize("NFC"); const syllableUnits = mapSyllables(definition.syllableUnits, referenceText, display.showSyllableBreaks)
  const media = asRecord(definition.media); const referenceImage = mapMedia(media?.referenceImage, "REFERENCE_IMAGE"); const referenceAudio = mapMedia(media?.referenceAudio, "REFERENCE_AUDIO"); const instructionAudio = mapMedia(media?.instructionAudio, "INSTRUCTION_AUDIO"); const hintMedia = mapMedia(hint.media, "HINT_AUDIO")
  if (!syllableUnits || !referenceImage || !referenceAudio || !instructionAudio || !hintMedia || (hint.type === "PLAY_REFERENCE_AUDIO" && hintMedia.length === 0)) return { ok: false, message: "Suku kata atau media item ini tidak sah." }
  return { ok: true, question: { itemId: item.id, sequence: item.sequence, contentMode, referenceText, repetitionCount: definition.repetitionCount, canvasWidth: canvas.width, canvasHeight: canvas.height, writingLayout: layout, referenceDisplay: display, syllableUnits, writingDirection: "LEFT_TO_RIGHT", tools, completion, allowRetry: definition.allowRetry, clearOnRetry: definition.clearOnRetry, hintType: hint.type, hintMedia, media: { referenceImage, referenceAudio, instructionAudio }, instructions: item.questionBankItem.instructions } }
}

export function createCopyWritingState(question: CopyWritingQuestion): CopyWritingState { return { strokes: [], redoStrokes: [], selectedTool: "PEN", strokeWidth: question.tools.defaultStrokeWidth, submitted: false, isComplete: null, validation: null, attemptCount: 0, completed: false, feedback: null } }
export function addCopyWritingStroke(state: CopyWritingState, stroke: CopyWritingStroke): CopyWritingState { return state.submitted ? state : { ...state, strokes: [...state.strokes, stroke], redoStrokes: [], validation: null } }
export function eraseCopyWritingStroke(state: CopyWritingState, strokeId: string): CopyWritingState { const stroke = state.strokes.find((entry) => entry.id === strokeId); return !stroke || state.submitted ? state : { ...state, strokes: state.strokes.filter((entry) => entry.id !== strokeId), redoStrokes: [...state.redoStrokes, stroke], validation: null } }
export function undoCopyWriting(state: CopyWritingState): CopyWritingState { const stroke = state.strokes.at(-1); return !stroke ? state : { ...state, strokes: state.strokes.slice(0, -1), redoStrokes: [...state.redoStrokes, stroke] } }
export function redoCopyWriting(state: CopyWritingState): CopyWritingState { const stroke = state.redoStrokes.at(-1); return !stroke ? state : { ...state, strokes: [...state.strokes, stroke], redoStrokes: state.redoStrokes.slice(0, -1) } }
export function clearCopyWriting(state: CopyWritingState): CopyWritingState { return { ...state, strokes: [], redoStrokes: [], submitted: false, isComplete: null, validation: null, completed: false, feedback: null } }
export function usedCopyWritingRegions(state: CopyWritingState): ReadonlySet<number> { return new Set(state.strokes.map((stroke) => stroke.regionIndex)) }
export function getCopyWritingSettings(activity: { attemptsAllowed: number | null; allowRetry: boolean; showImmediateFeedback: boolean; configuration: unknown }, question: CopyWritingQuestion): CopyWritingSettings { return { attemptsAllowed: activity.attemptsAllowed, allowRetry: activity.allowRetry && question.allowRetry, showImmediateFeedback: activity.showImmediateFeedback } }
export function canRetryCopyWriting(state: CopyWritingState, settings: CopyWritingSettings): boolean { return state.submitted && state.isComplete === false && settings.allowRetry && (settings.attemptsAllowed === null || state.attemptCount < settings.attemptsAllowed) }
export function submitCopyWriting(state: CopyWritingState, question: CopyWritingQuestion, settings: CopyWritingSettings): CopyWritingState { if (state.submitted) return state; if (state.strokes.length === 0) return { ...state, validation: "EMPTY", feedback: "Sila tulis dahulu." }; const used = usedCopyWritingRegions(state); const requiredRegions = question.completion.requireAllRepetitions ? question.repetitionCount : question.completion.minimumWritingRegionsUsed ?? 0; if (state.strokes.length < question.completion.minimumStrokeCount || used.size < requiredRegions) return { ...state, submitted: true, isComplete: false, validation: "REGIONS", attemptCount: state.attemptCount + 1, completed: !settings.showImmediateFeedback || !settings.allowRetry || (settings.attemptsAllowed !== null && state.attemptCount + 1 >= settings.attemptsAllowed), feedback: settings.showImmediateFeedback ? "Cuba lengkapkan semua ruang tulisan." : "Tulisan direkod untuk semakan sesi ini." }; return { ...state, submitted: true, isComplete: true, validation: null, attemptCount: state.attemptCount + 1, completed: true, feedback: settings.showImmediateFeedback ? "Bagus! Semua ruang tulisan telah dilengkapkan." : "Tulisan direkod untuk semakan sesi ini." } }
export function retryCopyWriting(state: CopyWritingState, question: CopyWritingQuestion): CopyWritingState { return question.clearOnRetry ? { ...clearCopyWriting(state), attemptCount: state.attemptCount } : { ...state, submitted: false, isComplete: null, validation: null, completed: false, feedback: null } }
export function updateCopyWritingSession(session: CopyWritingSessionState, itemId: string, state: CopyWritingState): CopyWritingSessionState { return { ...session, [itemId]: state } }
export function buildCopyWritingCompletionSummary(session: CopyWritingSessionState, questions: readonly CopyWritingQuestion[]): ActivityCompletionSummary { const states = questions.map((question) => session[question.itemId]).filter((state): state is CopyWritingState => Boolean(state)); return { totalQuestions: questions.length, completedQuestions: states.filter((state) => state.completed).length, correctQuestions: states.filter((state) => state.isComplete === true).length, incorrectQuestions: states.filter((state) => state.isComplete === false).length, totalAttempts: states.reduce((total, state) => total + state.attemptCount, 0) } }
