import type {
  AdminEntityConfig,
  BackendCapability,
} from "@/features/admin/types/admin.types";

export const accountStatuses = [
  { label: "Aktif", value: "ACTIVE" },
  { label: "Digantung", value: "SUSPENDED" },
  { label: "Diarkibkan", value: "ARCHIVED" },
];

export const genderOptions = [
  { label: "Lelaki", value: "MALE" },
  { label: "Perempuan", value: "FEMALE" },
];

export const adminEntities: AdminEntityConfig[] = [
  {
    key: "schools",
    title: "Sekolah",
    singular: "Sekolah",
    description: "Urus sekolah menggunakan endpoint /api/schools.",
    path: "/admin/sekolah",
    endpoint: "/schools",
    roles: ["SUPER_ADMIN", "ADMIN"],
    searchable: true,
    statusFilter: true,
    create: true,
    edit: true,
    lifecycle: true,
    columns: [
      { key: "schoolName", label: "Nama" },
      { key: "schoolCode", label: "Kod" },
      { key: "address", label: "Alamat" },
      { key: "accountStatus", label: "Status", kind: "status" },
      { key: "createdAt", label: "Dicipta", kind: "date" },
    ],
    fields: [
      { name: "schoolCode", label: "Kod sekolah", required: true },
      { name: "schoolName", label: "Nama sekolah", required: true },
      { name: "principalName", label: "Nama pengetua" },
      { name: "address", label: "Alamat", type: "textarea", required: true },
      { name: "phone", label: "Telefon", required: true },
      { name: "contactEmail", label: "E-mel perhubungan", type: "email" },
      { name: "logo", label: "URL logo" },
    ],
    editFieldNames: ["schoolCode", "schoolName", "principalName", "address", "phone", "contactEmail", "logo"],
  },
  {
    key: "admins",
    title: "Pentadbir",
    singular: "Pentadbir",
    description: "Pengurusan akaun Admin. Backend menghadkan endpoint ini kepada SUPER_ADMIN.",
    path: "/admin/pentadbir",
    endpoint: "/admins",
    roles: ["SUPER_ADMIN"],
    searchable: true,
    statusFilter: true,
    create: true,
    edit: true,
    lifecycle: true,
    resendSetup: true,
    columns: [
      { key: "fullName", label: "Nama" },
      { key: "user.email", label: "E-mel" },
      { key: "position", label: "Jawatan" },
      { key: "user.accountStatus", label: "Status", kind: "status" },
      { key: "createdAt", label: "Dicipta", kind: "date" },
    ],
    fields: [
      { name: "fullName", label: "Nama penuh", required: true },
      { name: "email", label: "E-mel", type: "email", required: true },
      { name: "phone", label: "Telefon" },
      { name: "position", label: "Jawatan" },
      { name: "avatar", label: "URL avatar" },
    ],
    editFieldNames: ["fullName", "email", "phone", "position", "avatar"],
  },
  {
    key: "teachers",
    title: "Guru",
    singular: "Guru",
    description: "Urus akaun guru yang menggunakan platform Digital MoLIB.",
    path: "/admin/guru",
    endpoint: "/teachers",
    roles: ["SUPER_ADMIN", "ADMIN"],
    searchable: true,
    statusFilter: true,
    create: true,
    edit: true,
    lifecycle: true,
    resendSetup: true,
    columns: [
      { key: "fullName", label: "Guru" },
      { key: "email", label: "E-mel" },
      { key: "school.schoolName", label: "Sekolah" },
      { key: "accountStatus", label: "Status", kind: "status" },
      { key: "lastLogin", label: "Log Masuk Terakhir", kind: "date" },
    ],
    fields: [
      { name: "schoolId", label: "ID sekolah", required: true },
      { name: "teacherId", label: "ID guru", required: true },
      { name: "fullName", label: "Nama penuh", required: true },
      { name: "gender", label: "Jantina", type: "select", options: genderOptions, required: true },
      { name: "email", label: "E-mel", type: "email", required: true },
      { name: "phone", label: "Telefon" },
      { name: "position", label: "Jawatan" },
      { name: "avatar", label: "URL avatar" },
    ],
    editFieldNames: ["schoolId", "fullName", "email", "phone"],
  },
  {
    key: "students",
    title: "Murid",
    singular: "Murid",
    description: "Urus murid, kelas, status akaun, pautan ibu bapa dan reset PIN.",
    path: "/admin/murid",
    endpoint: "/students",
    roles: ["SUPER_ADMIN", "ADMIN"],
    searchable: true,
    statusFilter: true,
    create: true,
    edit: true,
    lifecycle: true,
    columns: [
      { key: "studentId", label: "ID Murid" },
      { key: "fullName", label: "Nama" },
      { key: "class.className", label: "Kelas" },
      { key: "school.schoolName", label: "Sekolah" },
      { key: "user.accountStatus", label: "Status", kind: "status" },
    ],
    fields: [
      { name: "schoolId", label: "ID sekolah", required: true },
      { name: "classId", label: "ID kelas", required: true },
      { name: "studentId", label: "ID murid", required: true },
      { name: "fullName", label: "Nama penuh", required: true },
      { name: "gender", label: "Jantina", type: "select", options: genderOptions, required: true },
      { name: "birthDate", label: "Tarikh lahir", type: "date" },
      { name: "avatar", label: "URL avatar" },
    ],
    editFieldNames: ["studentId", "fullName", "gender", "birthDate", "avatar"],
    detailTabs: ["Maklumat", "Ibu Bapa", "Tugasan", "Penilaian", "Kemajuan PBD"],
  },
  {
    key: "parents",
    title: "Ibu Bapa",
    singular: "Ibu Bapa",
    description: "Urus akaun ibu bapa dan pautan anak.",
    path: "/admin/ibu-bapa",
    endpoint: "/parents",
    roles: ["SUPER_ADMIN", "ADMIN"],
    searchable: true,
    statusFilter: true,
    create: true,
    edit: true,
    lifecycle: true,
    resendSetup: true,
    columns: [
      { key: "fullName", label: "Nama" },
      { key: "phone", label: "Telefon" },
      { key: "user.email", label: "E-mel" },
      { key: "occupation", label: "Pekerjaan" },
      { key: "user.accountStatus", label: "Status", kind: "status" },
    ],
    fields: [
      { name: "fullName", label: "Nama penuh", required: true },
      { name: "phone", label: "Telefon", required: true },
      { name: "email", label: "E-mel", type: "email" },
      { name: "occupation", label: "Pekerjaan" },
      { name: "address", label: "Alamat", type: "textarea" },
      { name: "avatar", label: "URL avatar" },
    ],
    editFieldNames: ["fullName", "phone", "email", "occupation", "address", "avatar"],
  },
  {
    key: "classes",
    title: "Kelas",
    singular: "Kelas",
    description: "Urus kelas, guru kelas, kapasiti dan senarai murid.",
    path: "/admin/kelas",
    endpoint: "/classes",
    roles: ["SUPER_ADMIN", "ADMIN"],
    searchable: true,
    statusFilter: true,
    create: true,
    edit: true,
    lifecycle: true,
    columns: [
      { key: "className", label: "Kelas" },
      { key: "yearLevel", label: "Tahun" },
      { key: "academicYear", label: "Akademik" },
      { key: "teacher.fullName", label: "Guru" },
      { key: "accountStatus", label: "Status", kind: "status" },
    ],
    fields: [
      { name: "schoolId", label: "ID sekolah", required: true },
      { name: "teacherId", label: "ID guru", required: true },
      { name: "className", label: "Nama kelas", required: true },
      { name: "yearLevel", label: "Tahun", type: "number", required: true },
      { name: "academicYear", label: "Tahun akademik", type: "number", required: true },
      { name: "capacity", label: "Kapasiti", type: "number" },
    ],
    editFieldNames: ["className", "yearLevel", "academicYear", "capacity"],
  },
  {
    key: "assignments",
    title: "Tugasan",
    singular: "Tugasan",
    description: "Pemantauan tugasan. Backend juga menyokong penciptaan oleh Admin/Guru.",
    path: "/admin/tugasan",
    endpoint: "/assignments",
    roles: ["SUPER_ADMIN", "ADMIN"],
    searchable: true,
    statusFilter: true,
    columns: [
      { key: "title", label: "Tajuk" },
      { key: "status", label: "Status", kind: "status" },
      { key: "priority", label: "Keutamaan" },
      { key: "createdAt", label: "Dicipta", kind: "date" },
    ],
    unsupportedActions: ["Close/cancel/archive lifecycle endpoints are not present."],
  },
  {
    key: "submissions",
    title: "Penghantaran",
    singular: "Penghantaran",
    description: "Pemantauan penghantaran. Review endpoints wujud tetapi UI Admin menyembunyikan tindakan pedagogi.",
    path: "/admin/penghantaran",
    endpoint: "/submissions",
    roles: ["SUPER_ADMIN", "ADMIN"],
    searchable: true,
    statusFilter: true,
    columns: [
      { key: "assignment.title", label: "Tugasan" },
      { key: "student.fullName", label: "Murid" },
      { key: "status", label: "Status", kind: "status" },
      { key: "submittedAt", label: "Dihantar", kind: "date" },
    ],
    unsupportedActions: ["Admin review controls intentionally hidden unless a dedicated admin review workflow exists."],
  },
  {
    key: "assessments",
    title: "Penilaian",
    singular: "Penilaian",
    description: "Pantau pentaksiran dan butiran markah yang dibenarkan backend.",
    path: "/admin/penilaian",
    endpoint: "/assessments",
    roles: ["SUPER_ADMIN", "ADMIN"],
    searchable: true,
    statusFilter: true,
    columns: [
      { key: "student.fullName", label: "Murid" },
      { key: "status", label: "Status", kind: "status" },
      { key: "finalMarks", label: "Markah" },
      { key: "percentage", label: "Peratus" },
      { key: "assessedAt", label: "Dinilai", kind: "date" },
    ],
    unsupportedActions: ["Arbitrary mark editing is not exposed."],
  },
  {
    key: "pbdEvidence",
    title: "Bukti PBD",
    singular: "Bukti PBD",
    description: "Pantau bukti PBD dan status kesahan.",
    path: "/admin/pbd/bukti",
    endpoint: "/pbd/evidence",
    roles: ["SUPER_ADMIN", "ADMIN"],
    searchable: true,
    columns: [
      { key: "student.fullName", label: "Murid" },
      { key: "evidenceType", label: "Jenis" },
      { key: "strength", label: "Kekuatan" },
      { key: "observedAt", label: "Tarikh", kind: "date" },
    ],
  },
  {
    key: "pbdMastery",
    title: "Penguasaan PBD",
    singular: "Penguasaan PBD",
    description: "Pantau tahap penguasaan semasa dan trend.",
    path: "/admin/pbd",
    endpoint: "/pbd/mastery",
    roles: ["SUPER_ADMIN", "ADMIN"],
    searchable: true,
    statusFilter: true,
    columns: [
      { key: "student.fullName", label: "Murid" },
      { key: "currentLevel", label: "Tahap" },
      { key: "status", label: "Status", kind: "status" },
      { key: "trend", label: "Trend" },
      { key: "updatedAt", label: "Dikemas kini", kind: "date" },
    ],
    unsupportedActions: ["Teacher-only confirmation/override controls are hidden for Admin."],
  },
  {
    key: "notifications",
    title: "Notifikasi",
    singular: "Notifikasi",
    description: "Notifikasi pengguna semasa daripada Phase 26.",
    path: "/admin/notifikasi",
    endpoint: "/notifications",
    roles: ["SUPER_ADMIN", "ADMIN"],
    searchable: true,
    columns: [
      { key: "title", label: "Tajuk" },
      { key: "type", label: "Jenis" },
      { key: "priority", label: "Keutamaan" },
      { key: "readAt", label: "Dibaca", kind: "date" },
    ],
  },
  {
    key: "announcements",
    title: "Pengumuman",
    singular: "Pengumuman",
    description: "Senarai pengumuman dan sasaran yang dibenarkan.",
    path: "/admin/pengumuman",
    endpoint: "/announcements",
    roles: ["SUPER_ADMIN", "ADMIN"],
    searchable: true,
    create: true,
    columns: [
      { key: "title", label: "Tajuk" },
      { key: "priority", label: "Keutamaan" },
      { key: "pinned", label: "Pin" },
      { key: "publishedAt", label: "Diterbitkan", kind: "date" },
    ],
    fields: [
      { name: "title", label: "Tajuk", required: true },
      { name: "body", label: "Kandungan", type: "textarea", required: true },
      { name: "priority", label: "Keutamaan", type: "select", options: [
        { label: "Normal", value: "NORMAL" },
        { label: "Tinggi", value: "HIGH" },
        { label: "Segera", value: "URGENT" },
      ] },
      { name: "schoolId", label: "ID sekolah" },
    ],
    unsupportedActions: ["Target array authoring uses backend validation; advanced target-count preview endpoint is not present."],
  },
  {
    key: "aiOutputs",
    title: "Draf AI",
    singular: "Draf AI",
    description: "Draf AI - Semakan manusia diperlukan.",
    path: "/admin/ai",
    endpoint: "/ai/outputs",
    roles: ["SUPER_ADMIN", "ADMIN"],
    searchable: false,
    columns: [
      { key: "featureType", label: "Ciri" },
      { key: "status", label: "Status", kind: "status" },
      { key: "riskLevel", label: "Risiko" },
      { key: "createdAt", label: "Dicipta", kind: "date" },
    ],
    unsupportedActions: ["No provider API key, arbitrary prompt, model selection, or auto-publish controls are exposed."],
  },
  {
    key: "auditLogs",
    title: "Audit Log",
    singular: "Audit Log",
    description: "Log audit tersanitasi daripada endpoint /api/audit-logs.",
    path: "/admin/audit",
    endpoint: "/audit-logs",
    roles: ["SUPER_ADMIN", "ADMIN"],
    searchable: true,
    columns: [
      { key: "action", label: "Tindakan" },
      { key: "resourceType", label: "Sumber" },
      { key: "actor.role", label: "Peranan", kind: "role" },
      { key: "createdAt", label: "Tarikh", kind: "date" },
    ],
  },
];

export const unsupportedBackendCapabilities: BackendCapability[] = [
  {
    feature: "System settings",
    supported: false,
    note: "No dedicated backend settings route exists; the UI shows a safe unavailable state.",
  },
  {
    feature: "PDF export",
    supported: false,
    note: "Report APIs return DTO/chart data only; PDF generation is out of scope.",
  },
  {
    feature: "Excel export",
    supported: false,
    note: "No Excel endpoint is implemented.",
  },
  {
    feature: "AI usage totals/cost",
    supported: false,
    note: "AI output listing exists; aggregate usage/cost endpoint is not present.",
  },
  {
    feature: "Announcement target count preview",
    supported: false,
    note: "Create/publish endpoints exist, but no preview-count endpoint is available.",
  },
];

export function getAdminEntity(key: AdminEntityConfig["key"]): AdminEntityConfig {
  const config = adminEntities.find((entity) => entity.key === key);

  if (!config) {
    throw new Error(`Unknown admin entity: ${key}`);
  }

  return config;
}
