import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeader } from "@/components/shared/PageHeader";
import { ErrorState } from "@/components/shared/ErrorState";
import { LoadingSpinner } from "@/components/shared/LoadingSpinner";
import { aiOutput, aiOutputs, aiPost } from "@/features/ai/api/ai.api";
import { AiHumanReviewBanner } from "@/features/ai/components/AiHumanReviewBanner";
const text=(v:unknown)=>typeof v==="string"||typeof v==="number"?String(v):"—";
export function AiOutputListPage(){const q=useQuery({queryKey:["ai","outputs"],queryFn:aiOutputs});if(q.isLoading)return <LoadingSpinner label="Memuatkan draf AI..."/>;if(q.error)return <ErrorState actionLabel="Cuba lagi" onAction={()=>void q.refetch()}/>;return <main className="space-y-6"><PageHeader title="Draf AI" description="Draf yang dihasilkan melalui backend untuk semakan."/><AiHumanReviewBanner/><div className="grid gap-4 md:grid-cols-2">{q.data?.map(row=>{const req=typeof row.aiRequest==="object"&&row.aiRequest!==null?row.aiRequest as Record<string,unknown>:{};return <Card key={text(row.id)}><CardHeader><CardTitle>{text(req.featureType)}</CardTitle><CardDescription>{text(row.reviewStatus)} · {text(row.createdAt)}</CardDescription></CardHeader><CardContent><p className="mb-3 text-sm text-muted-foreground">{text(row.safeSummary)}</p><Button asChild size="sm"><Link to={`draf/${text(row.id)}`}>Semak draf</Link></Button></CardContent></Card>})}</div></main>}
export function AiOutputDetailPage(){const {draftId=""}=useParams();const client=useQueryClient();const q=useQuery({queryKey:["ai","output",draftId],queryFn:()=>aiOutput(draftId),enabled:Boolean(draftId)});const action=useMutation({mutationFn:({path,body}:{path:string;body?:Record<string,unknown>})=>aiPost(path,body),onSuccess:()=>void client.invalidateQueries({queryKey:["ai"]})});if(q.isLoading)return <LoadingSpinner label="Memuatkan draf..."/>;if(q.error)return <ErrorState/>;return <main className="space-y-6"><PageHeader title="Semak Draf AI"/><AiHumanReviewBanner/><Card><CardContent className="space-y-3 p-6"><p>{text(q.data?.safeSummary)}</p><p className="text-sm text-muted-foreground">Output berstruktur tersedia untuk semakan backend.</p><div className="flex flex-wrap gap-2"><Button disabled={action.isPending} onClick={()=>action.mutate({path:`/ai/outputs/${draftId}/approve`,body:{}})}>Luluskan draf</Button><Button variant="destructive" disabled={action.isPending} onClick={()=>action.mutate({path:`/ai/outputs/${draftId}/reject`,body:{reviewNotes:"Tidak sesuai untuk digunakan."}})}>Tolak</Button><Button variant="outline" disabled={action.isPending} onClick={()=>action.mutate({path:`/ai/outputs/${draftId}/archive`,body:{}})}>Arkib</Button></div></CardContent></Card></main>}
export function AiDraftGeneratorPage({path,title}:{path:string;title:string}){const [count,setCount]=useState("1");const [instructions,setInstructions]=useState("");const action=useMutation({mutationFn:()=>aiPost(path,{count:Number(count),additionalInstructions:instructions||undefined})});return <main className="space-y-6"><PageHeader title={title}/><AiHumanReviewBanner/><Card><CardContent className="space-y-4 p-6"><label className="block text-sm">Bilangan draf (1–10)<Input type="number" min="1" max="10" value={count} onChange={e=>setCount(e.target.value)}/></label><label className="block text-sm">Arahan tambahan<Input value={instructions} maxLength={1000} onChange={e=>setInstructions(e.target.value)}/></label><Button disabled={action.isPending} onClick={()=>action.mutate()}>Jana draf untuk semakan</Button>{action.error?<p className="text-sm text-destructive">Permintaan tidak dapat diproses.</p>:null}</CardContent></Card></main>}
