import { useState, type ChangeEvent } from "react";
import { Link, useParams } from "react-router-dom";
import { useForm } from "react-hook-form";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { PageHeader } from "@/components/shared/PageHeader";
import { EmptyState } from "@/components/shared/EmptyState";
import { ErrorState } from "@/components/shared/ErrorState";
import { LoadingSpinner } from "@/components/shared/LoadingSpinner";
import { TeacherStats, TeacherTable, SafeDetails } from "@/features/teacher/components/TeacherComponents";
import { useTeacherDashboard, useTeacherDetail, useTeacherList, useTeacherPost } from "@/features/teacher/hooks/use-teacher";
import { apiRequest } from "@/lib/api";
import { useQuery } from "@tanstack/react-query";
import type { TeacherResource } from "@/features/teacher/types/teacher.types";
import { isRecord, text } from "@/features/teacher/utils/teacher-record";

const titles: Record<TeacherResource, string> = { classes: "Kelas Saya", students: "Murid", activities: "Aktiviti Digital", assignments: "Tugasan", submissions: "Penghantaran", assessments: "Penilaian", evidence: "Bukti PBD", mastery: "Penguasaan PBD", notifications: "Notifikasi", announcements: "Pengumuman", ai: "Draf AI" };
const paths: Partial<Record<TeacherResource, string>> = { classes: "/guru/kelas", activities: "/guru/aktiviti", assignments: "/guru/tugasan", submissions: "/guru/penghantaran", assessments: "/guru/penilaian" };
function State({ loading, error, retry }: { loading: boolean; error: unknown; retry: () => void }) { if (loading) return <div className="grid min-h-48 place-items-center"><LoadingSpinner label="Memuatkan data..." /></div>; if (error) return <ErrorState title="Tidak dapat memuatkan data" description="Sila cuba lagi." actionLabel="Cuba lagi" onAction={retry} />; return null; }
export function TeacherDashboardPage() { const query = useTeacherDashboard(); const data = query.data ?? {}; const summary = isRecord(data.summary) ? data.summary : {}; const analytics = isRecord(data.analytics) ? data.analytics : {}; return <main className="space-y-6"><PageHeader title="Dashboard Guru" description="Ringkasan kelas dan kemajuan murid anda."/><State loading={query.isLoading} error={query.error} retry={() => void query.refetch()}/>{!query.isLoading && !query.error ? <><TeacherStats items={[{label:"Kelas Saya",value:summary.totalAssignedClasses},{label:"Jumlah Murid",value:summary.totalAssignedStudents},{label:"Semakan Menunggu",value:analytics.pendingReviews},{label:"Tugasan",value:analytics.assignments},{label:"Purata Penguasaan",value:analytics.averageMastery},{label:"Trend Penguasaan",value:analytics.masteryTrend}]}/><TeacherTable rows={Array.isArray(data.assignedClasses) ? data.assignedClasses.filter(isRecord) : []} detailPath={(row) => `/guru/kelas/${text(row.classId)}`} emptyMessage="Belum ada kelas ditetapkan."/></> : null}</main>; }
export function TeacherListPage({ resource }: { resource: TeacherResource }) { const [search, setSearch] = useState(""); const query = useTeacherList(resource, { page: 1, limit: 20, search: search || undefined }); const base = paths[resource]; return <main className="space-y-6"><PageHeader title={titles[resource]} description="Data dipaparkan mengikut skop kebenaran guru." actions={resource === "assignments" ? <Button asChild><Link to="/guru/tugasan/tambah">Tambah tugasan</Link></Button> : undefined}/><div className="max-w-md"><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari..." aria-label={`Cari ${titles[resource]}`}/></div><State loading={query.isLoading} error={query.error} retry={() => void query.refetch()}/>{!query.isLoading && !query.error ? <TeacherTable rows={query.data?.records ?? []} detailPath={base ? (row) => `${base}/${text(row.id ?? row.classId)}` : undefined} emptyMessage={`Tiada ${titles[resource].toLowerCase()}.`}/> : null}</main>; }
export function TeacherDetailPage({ resource }: { resource: TeacherResource }) { const params = useParams(); const id = params.classId ?? params.studentId ?? params.activityId ?? params.assignmentId ?? params.submissionId ?? params.assessmentId ?? ""; const query = useTeacherDetail(resource, id); return <main className="space-y-6"><PageHeader title={titles[resource]} description="Maklumat ini tertakluk kepada pengesahan skop oleh backend."/><State loading={query.isLoading} error={query.error} retry={() => void query.refetch()}/>{query.data ? <SafeDetails record={query.data}/> : null}{resource === "submissions" && id ? <ReviewPanel submissionId={id}/> : null}{resource === "assessments" && id ? <AdjustmentPanel assessmentId={id}/> : null}</main>; }
function ReviewPanel({ submissionId }: { submissionId: string }) { const post = useTeacherPost(); const [feedback, setFeedback] = useState(""); return <section className="space-y-3 rounded-lg border border-border p-4"><h2 className="font-semibold">Semakan keseluruhan</h2><p className="text-sm text-muted-foreground">Mulakan atau lengkapkan semakan hanya selepas backend mengesahkan status dan pemilikan semakan.</p><textarea className="min-h-24 w-full rounded-lg border border-border bg-background p-3 text-sm" value={feedback} onChange={(event: ChangeEvent<HTMLTextAreaElement>) => setFeedback(event.target.value)} placeholder="Maklum balas keseluruhan"/><div className="flex flex-wrap gap-2"><Button disabled={post.isPending} onClick={() => post.mutate({path:`/submissions/${submissionId}/start-review`})}>Mulakan semakan</Button><Button variant="outline" disabled={post.isPending || !feedback.trim()} onClick={() => post.mutate({path:`/submissions/${submissionId}/complete-review`,body:{decision:"APPROVED",overallFeedback:feedback}})}>Luluskan semakan</Button><Button variant="destructive" disabled={post.isPending || !feedback.trim()} onClick={() => post.mutate({path:`/submissions/${submissionId}/complete-review`,body:{decision:"REVISION_REQUIRED",overallFeedback:feedback}})}>Minta pembetulan</Button></div>{post.error ? <p className="text-sm text-destructive">{post.error.message}</p> : null}</section>; }
function AdjustmentPanel({ assessmentId }: { assessmentId: string }) { const post = useTeacherPost(); const form = useForm<{ newMarks: string; reason: string; notes: string }>({ defaultValues: { newMarks: "", reason: "", notes: "" } }); return <form className="space-y-3 rounded-lg border border-border p-4" onSubmit={form.handleSubmit((v) => post.mutate({path:`/assessments/${assessmentId}/adjustments`,body:{newMarks:Number(v.newMarks),reason:v.reason,notes:v.notes || null}}))}><h2 className="font-semibold">Pelarasan markah terkawal</h2><Label htmlFor="marks">Markah baharu</Label><Input id="marks" type="number" step="0.01" min="0" {...form.register("newMarks",{required:true})}/><Label htmlFor="reason">Sebab (kod backend)</Label><Input id="reason" {...form.register("reason",{required:true})}/><Label htmlFor="notes">Nota</Label><textarea id="notes" className="min-h-24 w-full rounded-lg border border-border bg-background p-3 text-sm" {...form.register("notes")}/><Button disabled={post.isPending} type="submit">Simpan pelarasan</Button>{post.error ? <p className="text-sm text-destructive">{post.error.message}</p> : null}</form>; }
export function TeacherAssignmentFormPage() { const post = useTeacherPost(); const form = useForm<{title:string;digitalActivityId:string;classIds:string;instructions:string}>({defaultValues:{title:"",digitalActivityId:"",classIds:"",instructions:""}}); return <main className="space-y-6"><PageHeader title="Tambah Tugasan" description="Tugasan diwujudkan sebagai DRAFT mengikut kontrak backend."/><form className="grid max-w-2xl gap-4 rounded-lg border border-border p-5" onSubmit={form.handleSubmit((v) => post.mutate({path:"/assignments",body:{title:v.title,digitalActivityId:v.digitalActivityId,classIds:v.classIds.split(",").map((id)=>id.trim()).filter(Boolean),studentIds:[],instructions:v.instructions || null,isRequired:true,showResultsAfterCompletion:false}}))}><Label>Tajuk<Input {...form.register("title",{required:true})}/></Label><Label>ID aktiviti digital diterbitkan<Input {...form.register("digitalActivityId",{required:true})}/></Label><Label>ID kelas dibenarkan (pisahkan koma)<Input {...form.register("classIds",{required:true})}/></Label><Label>Arahan<textarea className="min-h-24 w-full rounded-lg border border-border bg-background p-3 text-sm" {...form.register("instructions")}/></Label><Button disabled={post.isPending} type="submit">Simpan DRAFT</Button>{post.error ? <p className="text-sm text-destructive">{post.error.message}</p> : null}</form></main>; }
export function TeacherPbdPage() { return <TeacherListPage resource="mastery"/>; }
export function TeacherReportsPage() { return <main className="space-y-6"><PageHeader title="Laporan" description="Pilih murid atau kelas daripada halaman berkaitan untuk laporan berautoriti."/><EmptyState title="Pilih skop laporan" description="Laporan murid dan kelas menggunakan endpoint laporan yang dilindungi backend."/></main>; }
export function TeacherProfilePage() { const query = useQuery({queryKey:["teacher","profile"],queryFn:async()=>{const value=await apiRequest<unknown>("/profile/me"); return isRecord(value) && isRecord(value.profile) ? value.profile : {};}}); return <main className="space-y-6"><PageHeader title="Profil Saya" description="Maklumat akaun yang selamat sahaja dipaparkan."/><State loading={query.isLoading} error={query.error} retry={() => void query.refetch()}/>{query.data ? <SafeDetails record={query.data}/> : null}</main>; }
