import type { NextFunction, Request, Response } from "express";
import { AppError } from "../errors/app-error.js";
import { successResponse } from "../helpers/response.helper.js";
import type { AuthenticatedRequest } from "../middleware/auth.middleware.js";
import * as service from "../services/assessment.service.js";
import { adjustmentSchema, assessmentIdParamsSchema, assessmentItemParamsSchema, emptyBodySchema, invalidateSchema, listAssessmentsQuerySchema, manualScoreSchema, parentAssessmentParamsSchema } from "../validators/assessment.validator.js";

function context(req: AuthenticatedRequest): service.AssessmentContext { if (!req.auth) throw new AppError("AUTH_INVALID_TOKEN", 401, "Invalid or expired token."); return { actor: req.auth, requestIp: req.ip ?? null, userAgent: req.get("user-agent") ?? null }; }
function respond(res: Response, next: NextFunction, status: number, message: string, operation: () => Promise<unknown>): Promise<void> { return operation().then((data) => { successResponse(res, status, message, data); }).catch(next); }

export const listAssessmentsController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Senarai pentaksiran berjaya diperoleh.", () => service.listAssessments(listAssessmentsQuerySchema.parse(req.query), context(req as AuthenticatedRequest)));
export const getAssessmentController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Pentaksiran berjaya diperoleh.", () => service.getAssessment(assessmentIdParamsSchema.parse(req.params).assessmentId, context(req as AuthenticatedRequest)));
export const recalculateAssessmentController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Pentaksiran berjaya dikira semula.", () => { const { assessmentId } = assessmentIdParamsSchema.parse(req.params); emptyBodySchema.parse(req.body ?? {}); return service.recalculateAssessment(assessmentId, context(req as AuthenticatedRequest)); });
export const scoreManualItemController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Markah manual berjaya direkodkan.", () => { const params = assessmentItemParamsSchema.parse(req.params); return service.scoreManualItem(params.assessmentId, params.activityItemId, manualScoreSchema.parse(req.body), context(req as AuthenticatedRequest)); });
export const createAdjustmentController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 201, "Pelarasan markah berjaya direkodkan.", () => service.createAdjustment(assessmentIdParamsSchema.parse(req.params).assessmentId, adjustmentSchema.parse(req.body), context(req as AuthenticatedRequest)));
export const invalidateAssessmentController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Pentaksiran berjaya dibatalkan.", () => service.invalidateAssessment(assessmentIdParamsSchema.parse(req.params).assessmentId, invalidateSchema.parse(req.body ?? {}), context(req as AuthenticatedRequest)));
export const archiveAssessmentController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Pentaksiran berjaya diarkibkan.", () => { const { assessmentId } = assessmentIdParamsSchema.parse(req.params); emptyBodySchema.parse(req.body ?? {}); return service.archiveAssessment(assessmentId, context(req as AuthenticatedRequest)); });
export const listStudentAssessmentsController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Senarai pentaksiran murid berjaya diperoleh.", () => service.listStudentAssessments(context(req as AuthenticatedRequest)));
export const getStudentAssessmentController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Pentaksiran murid berjaya diperoleh.", () => service.getStudentAssessment(assessmentIdParamsSchema.parse(req.params).assessmentId, context(req as AuthenticatedRequest)));
export const listParentAssessmentsController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Senarai pentaksiran anak berjaya diperoleh.", () => service.listParentAssessments(parentAssessmentParamsSchema.parse(req.params).studentId, context(req as AuthenticatedRequest)));
