import type { NextFunction, Request, Response } from "express";
import { AppError } from "../errors/app-error.js";
import { successResponse } from "../helpers/response.helper.js";
import type { AuthenticatedRequest } from "../middleware/auth.middleware.js";
import * as service from "../services/assignment.service.js";
import { assignmentIdParamsSchema, childAssignmentParamsSchema, createAssignmentSchema, listAssignmentsQuerySchema, parentAssignmentsQuerySchema, studentAssignmentsQuerySchema, updateAssignmentSchema } from "../validators/assignment.validator.js";

function context(req: AuthenticatedRequest): service.Context { if (!req.auth) throw new AppError("AUTH_INVALID_TOKEN", 401, "Invalid or expired token."); return { actor: req.auth, requestIp: req.ip ?? null, userAgent: req.get("user-agent") ?? null }; }
function respond(res: Response, next: NextFunction, status: number, message: string, op: () => Promise<unknown>): Promise<void> { return op().then((data) => { successResponse(res, status, message, data); }).catch(next); }
export const createAssignmentController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 201, "Tugasan berjaya diwujudkan.", async () => ({ assignment: await service.createAssignment(createAssignmentSchema.parse(req.body), context(req as AuthenticatedRequest)) }));
export const listAssignmentsController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Senarai tugasan berjaya diperoleh.", async () => service.listAssignments(listAssignmentsQuerySchema.parse(req.query), context(req as AuthenticatedRequest)));
export const getAssignmentController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Tugasan berjaya diperoleh.", async () => ({ assignment: await service.getAssignment(assignmentIdParamsSchema.parse(req.params).assignmentId, context(req as AuthenticatedRequest)) }));
export const updateAssignmentController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Tugasan berjaya dikemas kini.", async () => ({ assignment: await service.updateAssignment(assignmentIdParamsSchema.parse(req.params).assignmentId, updateAssignmentSchema.parse(req.body), context(req as AuthenticatedRequest)) }));
export const listStudentAssignmentsController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Senarai tugasan murid berjaya diperoleh.", async () => service.listStudentAssignments(studentAssignmentsQuerySchema.parse(req.query), context(req as AuthenticatedRequest)));
export const getStudentAssignmentController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Tugasan murid berjaya diperoleh.", async () => ({ assignment: await service.getStudentAssignment(assignmentIdParamsSchema.parse(req.params).assignmentId, context(req as AuthenticatedRequest)) }));
export const getStudentAssignmentDeliveryController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Siaran tugasan berjaya diperoleh.", async () => service.getStudentAssignmentDelivery(assignmentIdParamsSchema.parse(req.params).assignmentId, context(req as AuthenticatedRequest)));
export const getParentChildrenAssignmentsController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Senarai tugasan anak berjaya diperoleh.", async () => { const { studentId } = childAssignmentParamsSchema.parse(req.params); return service.listParentChildrenAssignments(studentId, parentAssignmentsQuerySchema.parse(req.query), context(req as AuthenticatedRequest)); });
