import type { NextFunction, Request, Response } from "express";
import { AppError } from "../errors/app-error.js";
import { successResponse } from "../helpers/response.helper.js";
import type { AuthenticatedRequest } from "../middleware/auth.middleware.js";
import * as service from "../services/digitalActivity.service.js";
import { activityCurriculumLinkParamsSchema, activityItemParamsSchema, activityMediaParamsSchema, addDigitalActivityItemSchema, addDigitalActivityMediaSchema, createDigitalActivityCurriculumLinkSchema, createDigitalActivitySchema, digitalActivityIdParamsSchema, emptyBodySchema, listDigitalActivitiesQuerySchema, reorderDigitalActivityItemsSchema, reorderDigitalActivityMediaSchema, returnDraftSchema, updateDigitalActivityItemSchema, updateDigitalActivitySchema } from "../validators/digitalActivity.validator.js";

function context(req: AuthenticatedRequest): service.DigitalActivityAuditContext { if (!req.auth) throw new AppError("AUTH_INVALID_TOKEN", 401, "Invalid or expired token."); return { actor: req.auth, requestIp: req.ip ?? null, userAgent: req.get("user-agent") ?? null }; }
async function respond(res: Response, next: NextFunction, status: number, message: string, operation: () => Promise<unknown>): Promise<void> { try { successResponse(res, status, message, await operation()); } catch (caught) { next(caught); } }
export function createDigitalActivityController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 201, "Aktiviti digital berjaya diwujudkan.", async () => ({ activity: await service.createDigitalActivity(createDigitalActivitySchema.parse(req.body), context(req as AuthenticatedRequest)) })); }
export function listDigitalActivitiesController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Senarai aktiviti digital berjaya diperoleh.", () => service.listDigitalActivities(listDigitalActivitiesQuerySchema.parse(req.query), context(req as AuthenticatedRequest))); }
export function getDigitalActivityController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Aktiviti digital berjaya diperoleh.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); return { activity: await service.getDigitalActivity(activityId, context(req as AuthenticatedRequest)) }; }); }
export function getDigitalActivityPublishReadinessController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Kesediaan penerbitan aktiviti berjaya diperoleh.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); return { readiness: await service.getDigitalActivityPublishReadiness(activityId, context(req as AuthenticatedRequest)) }; }); }
export function updateDigitalActivityController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Aktiviti digital berjaya dikemas kini.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); return { activity: await service.updateDigitalActivity(activityId, updateDigitalActivitySchema.parse(req.body), context(req as AuthenticatedRequest)) }; }); }
export function deleteDigitalActivityController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Aktiviti berjaya dipadam.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); await service.deleteDigitalActivity(activityId, context(req as AuthenticatedRequest)); return { activityId }; }); }
export function submitReviewController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Aktiviti berjaya dihantar untuk semakan.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); emptyBodySchema.parse(req.body ?? {}); return { activity: await service.submitDigitalActivityForReview(activityId, context(req as AuthenticatedRequest)) }; }); }
export function returnDraftController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Aktiviti berjaya dikembalikan ke draf.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); const { comment } = returnDraftSchema.parse(req.body); return { activity: await service.returnDigitalActivityToDraft(activityId, comment, context(req as AuthenticatedRequest)) }; }); }
export function publishController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Aktiviti berjaya diterbitkan.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); emptyBodySchema.parse(req.body ?? {}); return { activity: await service.publishDigitalActivity(activityId, context(req as AuthenticatedRequest)) }; }); }
export function archiveController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Aktiviti berjaya diarkibkan.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); emptyBodySchema.parse(req.body ?? {}); return { activity: await service.archiveDigitalActivity(activityId, context(req as AuthenticatedRequest)) }; }); }
export function previewController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Pratonton aktiviti berjaya diperoleh.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); return service.previewDigitalActivity(activityId, context(req as AuthenticatedRequest)); }); }
export function historyController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Sejarah semakan berjaya diperoleh.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); return { reviewHistory: await service.listDigitalActivityReviewHistory(activityId, context(req as AuthenticatedRequest)) }; }); }
export function addCurriculumLinkController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 201, "Pautan kurikulum berjaya ditambah.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); return { link: await service.addDigitalActivityCurriculumLink(activityId, createDigitalActivityCurriculumLinkSchema.parse(req.body), context(req as AuthenticatedRequest)) }; }); }
export function listCurriculumLinksController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Pautan kurikulum berjaya diperoleh.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); return { links: await service.listDigitalActivityCurriculumLinks(activityId, context(req as AuthenticatedRequest)) }; }); }
export function removeCurriculumLinkController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Pautan kurikulum berjaya dibuang.", async () => { const { activityId, linkId } = activityCurriculumLinkParamsSchema.parse(req.params); await service.removeDigitalActivityCurriculumLink(activityId, linkId, context(req as AuthenticatedRequest)); return { linkId }; }); }
export function addItemController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 201, "Item aktiviti berjaya ditambah.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); return { item: await service.addDigitalActivityItem(activityId, addDigitalActivityItemSchema.parse(req.body), context(req as AuthenticatedRequest)) }; }); }
export function listItemsController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Item aktiviti berjaya diperoleh.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); return { items: await service.listDigitalActivityItems(activityId, context(req as AuthenticatedRequest)) }; }); }
export function updateItemController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Item aktiviti berjaya dikemas kini.", async () => { const { activityId, activityItemId } = activityItemParamsSchema.parse(req.params); return { item: await service.updateDigitalActivityItem(activityId, activityItemId, updateDigitalActivityItemSchema.parse(req.body), context(req as AuthenticatedRequest)) }; }); }
export function removeItemController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Item aktiviti berjaya dibuang.", async () => { const { activityId, activityItemId } = activityItemParamsSchema.parse(req.params); await service.removeDigitalActivityItem(activityId, activityItemId, context(req as AuthenticatedRequest)); return { activityItemId }; }); }
export function reorderItemsController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Turutan item berjaya dikemas kini.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); const { activityItemIds } = reorderDigitalActivityItemsSchema.parse(req.body); await service.reorderDigitalActivityItems(activityId, activityItemIds, context(req as AuthenticatedRequest)); return { activityItemIds }; }); }
export function addMediaController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 201, "Pautan media berjaya ditambah.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); return { media: await service.addDigitalActivityMedia(activityId, addDigitalActivityMediaSchema.parse(req.body), context(req as AuthenticatedRequest)) }; }); }
export function listMediaController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Pautan media berjaya diperoleh.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); return { media: await service.listDigitalActivityMedia(activityId, context(req as AuthenticatedRequest)) }; }); }
export function removeMediaController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Pautan media berjaya dibuang.", async () => { const { activityId, mediaLinkId } = activityMediaParamsSchema.parse(req.params); await service.removeDigitalActivityMedia(activityId, mediaLinkId, context(req as AuthenticatedRequest)); return { mediaLinkId }; }); }
export function reorderMediaController(req: Request, res: Response, next: NextFunction) { return respond(res, next, 200, "Turutan media berjaya dikemas kini.", async () => { const { activityId } = digitalActivityIdParamsSchema.parse(req.params); const { mediaLinkIds } = reorderDigitalActivityMediaSchema.parse(req.body); await service.reorderDigitalActivityMedia(activityId, mediaLinkIds, context(req as AuthenticatedRequest)); return { mediaLinkIds }; }); }
