import type { NextFunction, Request, Response } from "express";
import { AppError } from "../errors/app-error.js";
import { successResponse } from "../helpers/response.helper.js";
import type { AuthenticatedRequest } from "../middleware/auth.middleware.js";
import * as announcements from "../services/announcement.service.js";
import * as notifications from "../services/notification.service.js";
import { announcementSchema, emptySchema, notificationIdParamsSchema, notificationIdsSchema, notificationQuerySchema, preferencesSchema } from "../validators/notification.validator.js";
function context(req: AuthenticatedRequest): notifications.NotificationContext { if (!req.auth) throw new AppError("AUTH_INVALID_TOKEN", 401, "Token tidak sah atau telah tamat tempoh."); return { actor: req.auth, requestIp: req.ip ?? null, userAgent: req.get("user-agent") ?? null }; }
function respond(res: Response, next: NextFunction, status: number, message: string, operation: () => Promise<unknown>): void { void operation().then((data) => successResponse(res, status, message, data)).catch(next); }
export const listNotificationsController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Notifikasi berjaya diperoleh.", () => notifications.listNotifications(notificationQuerySchema.parse(req.query), context(req as AuthenticatedRequest)));
export const unreadNotificationsController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Notifikasi belum dibaca berjaya diperoleh.", () => notifications.listNotifications(notificationQuerySchema.parse(req.query), context(req as AuthenticatedRequest), true));
export const getNotificationController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Notifikasi berjaya diperoleh.", () => notifications.getNotification(notificationIdParamsSchema.parse(req.params).id, context(req as AuthenticatedRequest)));
export const markReadController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Notifikasi berjaya ditandakan sebagai dibaca.", () => notifications.markRead(notificationIdsSchema.parse(req.body).notificationIds, context(req as AuthenticatedRequest)));
export const readAllController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Semua notifikasi berjaya ditandakan sebagai dibaca.", () => { emptySchema.parse(req.body ?? {}); return notifications.markAllRead(context(req as AuthenticatedRequest)); });
export const archiveController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Notifikasi berjaya diarkibkan.", () => notifications.archiveNotifications(notificationIdsSchema.parse(req.body).notificationIds, context(req as AuthenticatedRequest)));
export const deleteController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Notifikasi berjaya dipadamkan.", () => notifications.deleteNotification(notificationIdParamsSchema.parse(req.params).id, context(req as AuthenticatedRequest)));
export const preferencesController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Keutamaan notifikasi berjaya diperoleh.", () => notifications.preferences(context(req as AuthenticatedRequest)));
export const updatePreferencesController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Keutamaan notifikasi berjaya dikemaskini.", () => notifications.updatePreferences(preferencesSchema.parse(req.body), context(req as AuthenticatedRequest)));
export const createAnnouncementController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 201, "Pengumuman berjaya dicipta.", () => announcements.createAnnouncement(announcementSchema.parse(req.body), context(req as AuthenticatedRequest)));
export const publishAnnouncementController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Pengumuman berjaya diterbitkan.", () => { emptySchema.parse(req.body ?? {}); return announcements.publishAnnouncement(notificationIdParamsSchema.parse(req.params).id, context(req as AuthenticatedRequest)); });
export const listAnnouncementsController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Pengumuman berjaya diperoleh.", () => announcements.listAnnouncements(context(req as AuthenticatedRequest)));
