import type { NextFunction, Request, Response } from "express";
import { AppError } from "../errors/app-error.js";
import { successResponse } from "../helpers/response.helper.js";
import type { AuthenticatedRequest } from "../middleware/auth.middleware.js";
import * as evidence from "../services/pbd-evidence.service.js";
import * as mastery from "../services/mastery.service.js";
import * as pbd from "../services/pbd.service.js";
import { classParamsSchema, decisionSchema, emptyBodySchema, evidenceIdParamsSchema, invalidateEvidenceSchema, listEvidenceQuerySchema, listMasteryQuerySchema, masteryIdParamsSchema, observationSchema, parentProgressParamsSchema, skillParamsSchema } from "../validators/pbd.validator.js";

function context(req: AuthenticatedRequest): mastery.PbdContext { if (!req.auth) throw new AppError("AUTH_INVALID_TOKEN", 401, "Invalid or expired token."); return { actor: req.auth, requestIp: req.ip ?? null, userAgent: req.get("user-agent") ?? null }; }
function respond(res: Response, next: NextFunction, status: number, message: string, operation: () => Promise<unknown>): Promise<void> { return operation().then((data) => { successResponse(res, status, message, data); }).catch(next); }
export const listEvidenceController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Senarai bukti PBD berjaya diperoleh.", () => pbd.listEvidence(listEvidenceQuerySchema.parse(req.query), context(req as AuthenticatedRequest)));
export const getEvidenceController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Bukti PBD berjaya diperoleh.", () => pbd.getEvidence(evidenceIdParamsSchema.parse(req.params).evidenceId, context(req as AuthenticatedRequest)));
export const observationController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 201, "Pemerhatian PBD berjaya direkodkan.", () => evidence.createObservation(observationSchema.parse(req.body), context(req as AuthenticatedRequest)));
export const invalidateEvidenceController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Bukti PBD berjaya dibatalkan.", () => evidence.invalidateEvidence(evidenceIdParamsSchema.parse(req.params).evidenceId, invalidateEvidenceSchema.parse(req.body ?? {}).reason ?? null, context(req as AuthenticatedRequest)));
export const listMasteryController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Senarai penguasaan berjaya diperoleh.", () => pbd.listMastery(listMasteryQuerySchema.parse(req.query), context(req as AuthenticatedRequest)));
export const getMasteryController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Rekod penguasaan berjaya diperoleh.", () => pbd.getMastery(masteryIdParamsSchema.parse(req.params).masteryId, context(req as AuthenticatedRequest)));
export const recalculateMasteryController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Penguasaan berjaya dikira semula.", () => { const id = masteryIdParamsSchema.parse(req.params).masteryId; emptyBodySchema.parse(req.body ?? {}); return mastery.recalculateMastery(id, context(req as AuthenticatedRequest)); });
export const confirmMasteryController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Penguasaan berjaya disahkan.", () => mastery.confirmMastery(masteryIdParamsSchema.parse(req.params).masteryId, decisionSchema.parse(req.body), context(req as AuthenticatedRequest)));
export const overrideMasteryController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Penguasaan berjaya dikemaskini.", () => mastery.overrideMastery(masteryIdParamsSchema.parse(req.params).masteryId, decisionSchema.parse(req.body), context(req as AuthenticatedRequest)));
export const archiveMasteryController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Penguasaan berjaya diarkibkan.", () => { const id = masteryIdParamsSchema.parse(req.params).masteryId; emptyBodySchema.parse(req.body ?? {}); return mastery.archiveMastery(id, context(req as AuthenticatedRequest)); });
export const studentProgressController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Kemajuan murid berjaya diperoleh.", () => pbd.studentProgress(context(req as AuthenticatedRequest)));
export const studentSkillProgressController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Kemajuan kemahiran berjaya diperoleh.", () => pbd.studentSkillProgress(skillParamsSchema.parse(req.params).remedialSkillId, context(req as AuthenticatedRequest)));
export const parentProgressController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Kemajuan anak berjaya diperoleh.", () => pbd.parentProgress(parentProgressParamsSchema.parse(req.params).studentId, context(req as AuthenticatedRequest)));
export const parentSkillProgressController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Kemajuan kemahiran anak berjaya diperoleh.", () => { const studentId = parentProgressParamsSchema.parse(req.params).studentId; const skillId = skillParamsSchema.parse(req.params).remedialSkillId; return pbd.parentSkillProgress(studentId, skillId, context(req as AuthenticatedRequest)); });
export const classProgressController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Kemajuan kelas berjaya diperoleh.", () => pbd.classProgress(classParamsSchema.parse(req.params).classId, context(req as AuthenticatedRequest)));
