import type { NextFunction, Request, Response } from "express";
import { AppError } from "../errors/app-error.js";
import { successResponse } from "../helpers/response.helper.js";
import type { AuthenticatedRequest } from "../middleware/auth.middleware.js";
import * as service from "../services/submission.service.js";
import { completeReviewSchema, emptyBodySchema, itemReviewSchema, listSubmissionsQuerySchema, parentSubmissionParamsSchema, submissionIdParamsSchema, submissionItemParamsSchema } from "../validators/submission.validator.js";

function context(req: AuthenticatedRequest): service.SubmissionContext { if (!req.auth) throw new AppError("AUTH_INVALID_TOKEN", 401, "Invalid or expired token."); return { actor: req.auth, requestIp: req.ip ?? null, userAgent: req.get("user-agent") ?? null }; }
function respond(res: Response, next: NextFunction, status: number, message: string, operation: () => Promise<unknown>): Promise<void> { return operation().then((data) => { successResponse(res, status, message, data); }).catch(next); }

export const listSubmissionsController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Senarai penyerahan berjaya diperoleh.", () => service.listSubmissions(listSubmissionsQuerySchema.parse(req.query), context(req as AuthenticatedRequest)));
export const getSubmissionController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Penyerahan berjaya diperoleh.", () => service.getSubmission(submissionIdParamsSchema.parse(req.params).submissionId, context(req as AuthenticatedRequest)));
export const startReviewController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Semakan penyerahan berjaya dimulakan.", () => { const { submissionId } = submissionIdParamsSchema.parse(req.params); emptyBodySchema.parse(req.body ?? {}); return service.startReview(submissionId, context(req as AuthenticatedRequest)); });
export const updateItemReviewController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Semakan item berjaya dikemas kini.", () => { const params = submissionItemParamsSchema.parse(req.params); return service.updateItemReview(params.submissionId, params.activityItemId, itemReviewSchema.parse(req.body), context(req as AuthenticatedRequest)); });
export const completeReviewController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Semakan penyerahan berjaya dilengkapkan.", () => service.completeReview(submissionIdParamsSchema.parse(req.params).submissionId, completeReviewSchema.parse(req.body), context(req as AuthenticatedRequest)));
export const cancelSubmissionController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Penyerahan berjaya dibatalkan.", () => { const { submissionId } = submissionIdParamsSchema.parse(req.params); emptyBodySchema.parse(req.body ?? {}); return service.cancelSubmission(submissionId, context(req as AuthenticatedRequest)); });
export const archiveSubmissionController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Penyerahan berjaya diarkibkan.", () => { const { submissionId } = submissionIdParamsSchema.parse(req.params); emptyBodySchema.parse(req.body ?? {}); return service.archiveSubmission(submissionId, context(req as AuthenticatedRequest)); });
export const listStudentSubmissionsController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Senarai penyerahan murid berjaya diperoleh.", () => service.listStudentSubmissions(context(req as AuthenticatedRequest)));
export const getStudentSubmissionController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Penyerahan murid berjaya diperoleh.", () => service.getStudentSubmission(submissionIdParamsSchema.parse(req.params).submissionId, context(req as AuthenticatedRequest)));
export const getStudentFeedbackController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Maklum balas penyerahan berjaya diperoleh.", () => service.getStudentFeedback(submissionIdParamsSchema.parse(req.params).submissionId, context(req as AuthenticatedRequest)));
export const reviseSubmissionController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 201, "Percubaan pembetulan berjaya dimulakan.", () => { const { submissionId } = submissionIdParamsSchema.parse(req.params); emptyBodySchema.parse(req.body ?? {}); return service.reviseSubmission(submissionId, context(req as AuthenticatedRequest)); });
export const listParentSubmissionsController = (req: Request, res: Response, next: NextFunction) => respond(res, next, 200, "Senarai penyerahan anak berjaya diperoleh.", () => { const { studentId } = parentSubmissionParamsSchema.parse(req.params); const query = listSubmissionsQuerySchema.pick({ page: true, limit: true }).parse(req.query); return service.listParentSubmissions(studentId, query, context(req as AuthenticatedRequest)); });
