import { AiFeatureType, UserRole } from "@prisma/client";
import { Router } from "express";
import * as controller from "../controllers/ai.controller.js";
import { authenticate, requirePasswordChanged } from "../middleware/auth.middleware.js";
import { requireRole } from "../middleware/role.middleware.js";
const router = Router(); const management = [UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.TEACHER] as const;
router.use(authenticate, requirePasswordChanged, requireRole(...management));
router.post("/question-bank/drafts", controller.draftController(AiFeatureType.QUESTION_DRAFT));
router.post("/digital-activities/drafts", controller.draftController(AiFeatureType.ACTIVITY_DRAFT));
router.post("/reading-passages/drafts", controller.draftController(AiFeatureType.READING_PASSAGE_DRAFT));
router.post("/reading-comprehension/drafts", controller.draftController(AiFeatureType.READING_COMPREHENSION_DRAFT));
router.post("/text/simplify", controller.draftController(AiFeatureType.TEXT_SIMPLIFICATION));
router.post("/curriculum/alignment-check", controller.draftController(AiFeatureType.CURRICULUM_ALIGNMENT));
router.post("/students/:studentId/practice-suggestions", controller.draftController(AiFeatureType.PRACTICE_SUGGESTION));
router.post("/submissions/:submissionId/feedback-draft", requireRole(UserRole.TEACHER), controller.draftController(AiFeatureType.FEEDBACK_DRAFT));
router.post("/parent-progress/:studentId/summary-draft", controller.draftController(AiFeatureType.PARENT_SUMMARY_DRAFT));
router.post("/audio/transcribe", controller.draftController(AiFeatureType.AUDIO_TRANSCRIPTION));
router.post("/audio/reading-analysis", controller.draftController(AiFeatureType.AUDIO_READING_ANALYSIS));
router.get("/outputs", controller.listOutputsController); router.get("/outputs/:outputId", controller.getOutputController); router.post("/outputs/:outputId/approve", controller.approveOutputController); router.post("/outputs/:outputId/reject", controller.rejectOutputController); router.post("/outputs/:outputId/archive", controller.archiveOutputController);
export default router;
