import { UserRole } from "@prisma/client";
import { Router } from "express";
import * as controller from "../controllers/digitalActivity.controller.js";
import { authenticate, requirePasswordChanged } from "../middleware/auth.middleware.js";
import { requireRole } from "../middleware/role.middleware.js";

const router = Router();
const manage = requireRole(UserRole.SUPER_ADMIN, UserRole.ADMIN);
const read = requireRole(UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.TEACHER);
const superAdmin = requireRole(UserRole.SUPER_ADMIN);
router.use(authenticate, requirePasswordChanged);
router.post("/", manage, controller.createDigitalActivityController);
router.get("/", read, controller.listDigitalActivitiesController);
router.get("/:activityId", read, controller.getDigitalActivityController);
router.patch("/:activityId", manage, controller.updateDigitalActivityController);
router.post("/:activityId/submit-review", manage, controller.submitReviewController);
router.post("/:activityId/return-draft", superAdmin, controller.returnDraftController);
router.post("/:activityId/publish", superAdmin, controller.publishController);
router.post("/:activityId/archive", superAdmin, controller.archiveController);
router.get("/:activityId/preview", read, controller.previewController);
router.get("/:activityId/review-history", read, controller.historyController);
router.post("/:activityId/curriculum-links", manage, controller.addCurriculumLinkController);
router.get("/:activityId/curriculum-links", read, controller.listCurriculumLinksController);
router.delete("/:activityId/curriculum-links/:linkId", manage, controller.removeCurriculumLinkController);
router.post("/:activityId/items", manage, controller.addItemController);
router.get("/:activityId/items", read, controller.listItemsController);
router.patch("/:activityId/items/reorder", manage, controller.reorderItemsController);
router.patch("/:activityId/items/:activityItemId", manage, controller.updateItemController);
router.delete("/:activityId/items/:activityItemId", manage, controller.removeItemController);
router.post("/:activityId/media", manage, controller.addMediaController);
router.get("/:activityId/media", read, controller.listMediaController);
router.patch("/:activityId/media/reorder", manage, controller.reorderMediaController);
router.delete("/:activityId/media/:mediaLinkId", manage, controller.removeMediaController);
export default router;
