import { UserRole } from "@prisma/client";
import { Router } from "express";
import * as controller from "../controllers/pbd.controller.js";
import { authenticate, requirePasswordChanged } from "../middleware/auth.middleware.js";
import { requireRole } from "../middleware/role.middleware.js";
const router = Router();
router.use(authenticate, requirePasswordChanged);
router.get("/evidence", requireRole(UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.TEACHER), controller.listEvidenceController);
router.get("/evidence/:evidenceId", requireRole(UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.TEACHER), controller.getEvidenceController);
router.post("/evidence/observations", requireRole(UserRole.TEACHER), controller.observationController);
router.post("/evidence/:evidenceId/invalidate", requireRole(UserRole.SUPER_ADMIN, UserRole.ADMIN), controller.invalidateEvidenceController);
router.get("/mastery", requireRole(UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.TEACHER), controller.listMasteryController);
router.get("/mastery/:masteryId", requireRole(UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.TEACHER), controller.getMasteryController);
router.post("/mastery/:masteryId/recalculate", requireRole(UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.TEACHER), controller.recalculateMasteryController);
router.post("/mastery/:masteryId/confirm", requireRole(UserRole.SUPER_ADMIN, UserRole.TEACHER), controller.confirmMasteryController);
router.post("/mastery/:masteryId/override", requireRole(UserRole.SUPER_ADMIN, UserRole.TEACHER), controller.overrideMasteryController);
router.post("/mastery/:masteryId/archive", requireRole(UserRole.SUPER_ADMIN), controller.archiveMasteryController);
router.get("/classes/:classId/progress", requireRole(UserRole.SUPER_ADMIN, UserRole.ADMIN, UserRole.TEACHER), controller.classProgressController);
export default router;
