import { assertSafeStorageKey } from "../storage/local-storage.adapter.js";
import { jsonByteSize } from "../utils/safe-json-schema.js";

export const FREE_HANDWRITING_MAX_BYTES = 16 * 1024;
export const FREE_HANDWRITING_MAX_DEPTH = 8;
const UNSAFE_TEXT = /(?:<\s*\/?\s*[a-z][^>]*>|\b(?:javascript|vbscript|data)\s*:|\bfunction\b|\beval\s*\(|\bscript\b|\bon[a-z]+\s*=|\b[a-z][a-z0-9+.-]*:\/\/)/i;
const FORBIDDEN_OBJECT_KEYS = new Set(["__proto__", "prototype", "constructor"]);

export type FreeHandwritingResponseMode = "LETTER" | "SYLLABLE" | "WORD" | "PHRASE" | "SENTENCE" | "SHORT_RESPONSE";
export type FreeHandwritingLineStyle = "NONE" | "BASELINE" | "TWO_LINE" | "THREE_LINE" | "FOUR_LINE";
export type FreeHandwritingHintType = "NONE" | "SHOW_PROMPT" | "PLAY_PROMPT_AUDIO" | "SHOW_PROMPT_IMAGE" | "SHOW_WRITING_LINES" | "EMPHASIZE_WRITING_AREA";
export type FreeHandwritingIssueCode = "FREE_HANDWRITING_CONTRACT_REQUIRED" | "FREE_HANDWRITING_CONFIGURATION_INVALID" | "FREE_HANDWRITING_CONFIGURATION_TOO_LARGE" | "FREE_HANDWRITING_CONFIGURATION_TOO_DEEP" | "FREE_HANDWRITING_UNSAFE_CONTENT" | "FREE_HANDWRITING_UNSUPPORTED_FIELD" | "FREE_HANDWRITING_RESPONSE_MODE_INVALID" | "FREE_HANDWRITING_PROMPT_REQUIRED" | "FREE_HANDWRITING_PROMPT_INVALID" | "FREE_HANDWRITING_CANVAS_INVALID" | "FREE_HANDWRITING_LAYOUT_INVALID" | "FREE_HANDWRITING_WRITING_DIRECTION_INVALID" | "FREE_HANDWRITING_TOOL_CONFIG_INVALID" | "FREE_HANDWRITING_COMPLETION_INVALID" | "FREE_HANDWRITING_REVIEW_CONFIG_INVALID" | "FREE_HANDWRITING_HINT_INVALID" | "FREE_HANDWRITING_MEDIA_INVALID";
export class FreeHandwritingContractError extends Error { constructor(readonly issues: readonly FreeHandwritingIssueCode[]) { super("Kontrak Free Handwriting tidak sah."); this.name = "FreeHandwritingContractError"; } }
export interface FreeHandwritingPrompt { text: string | null; showText: boolean; }
export interface FreeHandwritingCanvas { width: number; height: number; }
export interface FreeHandwritingLayout { lineStyle: FreeHandwritingLineStyle; lineCount: number; lineSpacing: number; showTopLine: boolean; showMidline: boolean; showBaseline: boolean; showDescenderLine: boolean; }
export interface FreeHandwritingTools { allowPen: boolean; allowEraser: boolean; allowUndo: boolean; allowRedo: boolean; allowClear: boolean; allowStrokeWidthChange: boolean; defaultStrokeWidth: number; }
export interface FreeHandwritingCompletion { minimumStrokeCount: number; minimumWritingRegionsUsed: number; requireAllWritingRegions: boolean; }
export interface FreeHandwritingMedia { promptImageKey: string | null; promptAudioKey: string | null; instructionAudioKey: string | null; supportingImageKey: string | null; supportingVideoKey: string | null; }
export interface FreeHandwritingHint { type: FreeHandwritingHintType; }
export interface FreeHandwritingDefinition { responseMode: FreeHandwritingResponseMode; prompt: FreeHandwritingPrompt; canvas: FreeHandwritingCanvas; writingLayout: FreeHandwritingLayout; writingDirection: "LEFT_TO_RIGHT"; tools: FreeHandwritingTools; completion: FreeHandwritingCompletion; teacherReviewRequired: boolean; allowRetry: boolean; clearOnRetry: boolean; hint: FreeHandwritingHint; media: FreeHandwritingMedia; }
export interface FreeHandwritingConfiguration { freeHandwriting: FreeHandwritingDefinition; }
export interface FreeHandwritingPreviewMedia { key: string; url: string | null; mimeType: string | null; altText: string | null; label: string | null; }
export interface FreeHandwritingPreviewMediaDescriptor { url: string | null; mimeType?: string | null; altText?: string | null; label?: string | null; }

function fail(...issues: FreeHandwritingIssueCode[]): never { throw new FreeHandwritingContractError(issues); }
function record(value: unknown, issue: FreeHandwritingIssueCode = "FREE_HANDWRITING_CONTRACT_REQUIRED"): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) fail(issue); const prototype = Object.getPrototypeOf(value); if (prototype !== Object.prototype && prototype !== null) fail(issue); return value as Record<string, unknown>; }
function safeJson(value: unknown, depth = 0, seen = new WeakSet<object>()): void { if (depth > FREE_HANDWRITING_MAX_DEPTH) fail("FREE_HANDWRITING_CONFIGURATION_TOO_DEEP"); if (value === null || typeof value === "boolean") return; if (typeof value === "number") { if (!Number.isFinite(value)) fail("FREE_HANDWRITING_CONFIGURATION_INVALID"); return; } if (typeof value === "string") { if (UNSAFE_TEXT.test(value)) fail("FREE_HANDWRITING_UNSAFE_CONTENT"); return; } if (!value || typeof value !== "object" || value instanceof Date || Buffer.isBuffer(value) || seen.has(value)) fail("FREE_HANDWRITING_CONFIGURATION_INVALID"); seen.add(value); if (Array.isArray(value)) { for (const entry of value) safeJson(entry, depth + 1, seen); return; } for (const [key, entry] of Object.entries(record(value, "FREE_HANDWRITING_CONFIGURATION_INVALID"))) { if (FORBIDDEN_OBJECT_KEYS.has(key) || UNSAFE_TEXT.test(key)) fail("FREE_HANDWRITING_UNSAFE_CONTENT"); safeJson(entry, depth + 1, seen); } }
function keys(value: Record<string, unknown>, allowed: readonly string[]): void { for (const key of Object.keys(value)) if (!allowed.includes(key)) fail("FREE_HANDWRITING_UNSUPPORTED_FIELD"); }
function text(value: unknown, issue: FreeHandwritingIssueCode, maximum: number): string { if (typeof value !== "string") fail(issue); const result = value.trim().normalize("NFC"); if (!result || result.length > maximum || UNSAFE_TEXT.test(result) || result.includes("{{") || result.includes("}}")) fail(issue); return result; }
function bool(value: unknown, issue: FreeHandwritingIssueCode): boolean { if (typeof value !== "boolean") fail(issue); return value; }
function optionalBool(value: unknown, fallback: boolean, issue: FreeHandwritingIssueCode): boolean { return value === undefined ? fallback : bool(value, issue); }
function mediaKey(value: unknown): string | null { if (value === undefined || value === null) return null; if (typeof value !== "string" || value !== value.trim() || !value || value.length > 512 || UNSAFE_TEXT.test(value)) fail("FREE_HANDWRITING_MEDIA_INVALID"); try { assertSafeStorageKey(value); } catch { fail("FREE_HANDWRITING_MEDIA_INVALID"); } return value; }
function parseMedia(value: unknown): FreeHandwritingMedia { if (value === undefined || value === null) return { promptImageKey: null, promptAudioKey: null, instructionAudioKey: null, supportingImageKey: null, supportingVideoKey: null }; const media = record(value, "FREE_HANDWRITING_MEDIA_INVALID"); keys(media, ["promptImageKey", "promptAudioKey", "instructionAudioKey", "supportingImageKey", "supportingVideoKey"]); return { promptImageKey: mediaKey(media.promptImageKey), promptAudioKey: mediaKey(media.promptAudioKey), instructionAudioKey: mediaKey(media.instructionAudioKey), supportingImageKey: mediaKey(media.supportingImageKey), supportingVideoKey: mediaKey(media.supportingVideoKey) }; }
function parsePrompt(value: unknown, media: FreeHandwritingMedia): FreeHandwritingPrompt { const prompt = record(value, "FREE_HANDWRITING_PROMPT_REQUIRED"); keys(prompt, ["text", "showText"]); const showText = bool(prompt.showText, "FREE_HANDWRITING_PROMPT_INVALID"); const promptText = prompt.text === undefined || prompt.text === null ? null : text(prompt.text, "FREE_HANDWRITING_PROMPT_INVALID", 500); if (!promptText && !media.promptImageKey && !media.promptAudioKey) fail("FREE_HANDWRITING_PROMPT_REQUIRED"); if (showText && !promptText) fail("FREE_HANDWRITING_PROMPT_REQUIRED"); return { text: promptText, showText }; }
function parseCanvas(value: unknown): FreeHandwritingCanvas { const canvas = record(value, "FREE_HANDWRITING_CANVAS_INVALID"); keys(canvas, ["width", "height"]); if (typeof canvas.width !== "number" || !Number.isInteger(canvas.width) || canvas.width < 400 || canvas.width > 2_000 || typeof canvas.height !== "number" || !Number.isInteger(canvas.height) || canvas.height < 250 || canvas.height > 1_800 || canvas.width / canvas.height < 0.5 || canvas.width / canvas.height > 6) fail("FREE_HANDWRITING_CANVAS_INVALID"); return { width: canvas.width, height: canvas.height }; }
function parseLayout(value: unknown, canvas: FreeHandwritingCanvas): FreeHandwritingLayout { const layout = record(value, "FREE_HANDWRITING_LAYOUT_INVALID"); keys(layout, ["lineStyle", "lineCount", "lineSpacing", "showTopLine", "showMidline", "showBaseline", "showDescenderLine"]); const lineStyle = layout.lineStyle; if (lineStyle !== "NONE" && lineStyle !== "BASELINE" && lineStyle !== "TWO_LINE" && lineStyle !== "THREE_LINE" && lineStyle !== "FOUR_LINE") fail("FREE_HANDWRITING_LAYOUT_INVALID"); if (typeof layout.lineCount !== "number" || !Number.isInteger(layout.lineCount) || layout.lineCount < 0 || layout.lineCount > 12 || (lineStyle !== "NONE" && layout.lineCount < 1) || (lineStyle === "NONE" && layout.lineCount !== 0)) fail("FREE_HANDWRITING_LAYOUT_INVALID"); if (typeof layout.lineSpacing !== "number" || !Number.isInteger(layout.lineSpacing) || layout.lineSpacing < 24 || layout.lineSpacing > 400 || (layout.lineCount > 0 && layout.lineCount * layout.lineSpacing > canvas.height)) fail("FREE_HANDWRITING_LAYOUT_INVALID"); const actual = [bool(layout.showTopLine, "FREE_HANDWRITING_LAYOUT_INVALID"), bool(layout.showMidline, "FREE_HANDWRITING_LAYOUT_INVALID"), bool(layout.showBaseline, "FREE_HANDWRITING_LAYOUT_INVALID"), bool(layout.showDescenderLine, "FREE_HANDWRITING_LAYOUT_INVALID")]; const expected: Record<FreeHandwritingLineStyle, readonly boolean[]> = { NONE: [false, false, false, false], BASELINE: [false, false, true, false], TWO_LINE: [true, false, true, false], THREE_LINE: [true, true, true, false], FOUR_LINE: [true, true, true, true] }; if (expected[lineStyle].some((entry, index) => entry !== actual[index])) fail("FREE_HANDWRITING_LAYOUT_INVALID"); return { lineStyle, lineCount: layout.lineCount, lineSpacing: layout.lineSpacing, showTopLine: actual[0]!, showMidline: actual[1]!, showBaseline: actual[2]!, showDescenderLine: actual[3]! }; }
function parseTools(value: unknown): FreeHandwritingTools { const tools = record(value, "FREE_HANDWRITING_TOOL_CONFIG_INVALID"); keys(tools, ["allowPen", "allowEraser", "allowUndo", "allowRedo", "allowClear", "allowStrokeWidthChange", "defaultStrokeWidth"]); const allowPen = bool(tools.allowPen, "FREE_HANDWRITING_TOOL_CONFIG_INVALID"); const allowUndo = bool(tools.allowUndo, "FREE_HANDWRITING_TOOL_CONFIG_INVALID"); const allowRedo = bool(tools.allowRedo, "FREE_HANDWRITING_TOOL_CONFIG_INVALID"); if (!allowPen || (allowRedo && !allowUndo) || typeof tools.defaultStrokeWidth !== "number" || !Number.isInteger(tools.defaultStrokeWidth) || tools.defaultStrokeWidth < 2 || tools.defaultStrokeWidth > 20) fail("FREE_HANDWRITING_TOOL_CONFIG_INVALID"); return { allowPen, allowEraser: bool(tools.allowEraser, "FREE_HANDWRITING_TOOL_CONFIG_INVALID"), allowUndo, allowRedo, allowClear: bool(tools.allowClear, "FREE_HANDWRITING_TOOL_CONFIG_INVALID"), allowStrokeWidthChange: bool(tools.allowStrokeWidthChange, "FREE_HANDWRITING_TOOL_CONFIG_INVALID"), defaultStrokeWidth: tools.defaultStrokeWidth }; }
function parseCompletion(value: unknown, layout: FreeHandwritingLayout): FreeHandwritingCompletion { const completion = record(value, "FREE_HANDWRITING_COMPLETION_INVALID"); keys(completion, ["minimumStrokeCount", "minimumWritingRegionsUsed", "requireAllWritingRegions"]); if (typeof completion.minimumStrokeCount !== "number" || !Number.isInteger(completion.minimumStrokeCount) || completion.minimumStrokeCount < 1 || completion.minimumStrokeCount > 1_000 || typeof completion.minimumWritingRegionsUsed !== "number" || !Number.isInteger(completion.minimumWritingRegionsUsed) || completion.minimumWritingRegionsUsed < 1) fail("FREE_HANDWRITING_COMPLETION_INVALID"); const regions = layout.lineCount || 1; const requireAllWritingRegions = bool(completion.requireAllWritingRegions, "FREE_HANDWRITING_COMPLETION_INVALID"); if (completion.minimumWritingRegionsUsed > regions || (requireAllWritingRegions && completion.minimumWritingRegionsUsed !== regions)) fail("FREE_HANDWRITING_COMPLETION_INVALID"); return { minimumStrokeCount: completion.minimumStrokeCount, minimumWritingRegionsUsed: completion.minimumWritingRegionsUsed, requireAllWritingRegions }; }
function parseHint(value: unknown, media: FreeHandwritingMedia): FreeHandwritingHint { if (value === undefined || value === null) return { type: "NONE" }; const hint = record(value, "FREE_HANDWRITING_HINT_INVALID"); keys(hint, ["type"]); if (hint.type !== "NONE" && hint.type !== "SHOW_PROMPT" && hint.type !== "PLAY_PROMPT_AUDIO" && hint.type !== "SHOW_PROMPT_IMAGE" && hint.type !== "SHOW_WRITING_LINES" && hint.type !== "EMPHASIZE_WRITING_AREA") fail("FREE_HANDWRITING_HINT_INVALID"); if ((hint.type === "PLAY_PROMPT_AUDIO" && !media.promptAudioKey) || (hint.type === "SHOW_PROMPT_IMAGE" && !media.promptImageKey)) fail("FREE_HANDWRITING_HINT_INVALID"); return { type: hint.type }; }

export function validateFreeHandwritingConfiguration(value: unknown): FreeHandwritingConfiguration { if (jsonByteSize(value) > FREE_HANDWRITING_MAX_BYTES) fail("FREE_HANDWRITING_CONFIGURATION_TOO_LARGE"); safeJson(value); const configuration = record(value); keys(configuration, ["freeHandwriting"]); const definition = record(configuration.freeHandwriting); keys(definition, ["responseMode", "prompt", "canvas", "writingLayout", "writingDirection", "tools", "completion", "teacherReviewRequired", "allowRetry", "clearOnRetry", "hint", "media"]); const responseMode = definition.responseMode; if (responseMode !== "LETTER" && responseMode !== "SYLLABLE" && responseMode !== "WORD" && responseMode !== "PHRASE" && responseMode !== "SENTENCE" && responseMode !== "SHORT_RESPONSE") fail("FREE_HANDWRITING_RESPONSE_MODE_INVALID"); const media = parseMedia(definition.media); const prompt = parsePrompt(definition.prompt, media); const canvas = parseCanvas(definition.canvas); const writingLayout = parseLayout(definition.writingLayout, canvas); if (definition.writingDirection !== "LEFT_TO_RIGHT") fail("FREE_HANDWRITING_WRITING_DIRECTION_INVALID"); const tools = parseTools(definition.tools); const completion = parseCompletion(definition.completion, writingLayout); if (typeof definition.teacherReviewRequired !== "boolean") fail("FREE_HANDWRITING_REVIEW_CONFIG_INVALID"); const hint = parseHint(definition.hint, media); return { freeHandwriting: { responseMode, prompt, canvas, writingLayout, writingDirection: "LEFT_TO_RIGHT", tools, completion, teacherReviewRequired: definition.teacherReviewRequired, allowRetry: optionalBool(definition.allowRetry, true, "FREE_HANDWRITING_CONFIGURATION_INVALID"), clearOnRetry: optionalBool(definition.clearOnRetry, false, "FREE_HANDWRITING_CONFIGURATION_INVALID"), hint, media } }; }
export function freeHandwritingMediaKeys(configuration: FreeHandwritingConfiguration): string[] { const media = configuration.freeHandwriting.media; return [media.promptImageKey, media.promptAudioKey, media.instructionAudioKey, media.supportingImageKey, media.supportingVideoKey].filter((key): key is string => key !== null); }
export async function validateFreeHandwritingMedia(configuration: FreeHandwritingConfiguration, exists: (key: string) => Promise<void>): Promise<void> { for (const key of freeHandwritingMediaKeys(configuration)) { try { await exists(key); } catch { fail("FREE_HANDWRITING_MEDIA_INVALID"); } } }
function safePreviewText(value: string | null | undefined): string | null { const localPath = /(?:^\/|^[A-Za-z]:[\\/]|(?:^|[\\/])(?:private|tmp|var|users)(?:[\\/]|$))/iu; return value === null || value === undefined || localPath.test(value) ? null : value; }
function previewMedia(key: string | null, media: ReadonlyMap<string, FreeHandwritingPreviewMediaDescriptor>): FreeHandwritingPreviewMedia[] { if (!key) return []; const descriptor = media.get(key); return [{ key, url: descriptor?.url ?? null, mimeType: descriptor?.mimeType ?? null, altText: safePreviewText(descriptor?.altText), label: safePreviewText(descriptor?.label) }]; }
export function freeHandwritingPreviewConfiguration(configuration: FreeHandwritingConfiguration, media: ReadonlyMap<string, FreeHandwritingPreviewMediaDescriptor>) { const definition = configuration.freeHandwriting; const promptImage = previewMedia(definition.media.promptImageKey, media); const promptAudio = previewMedia(definition.media.promptAudioKey, media); return { freeHandwriting: { responseMode: definition.responseMode, prompt: { ...definition.prompt, media: [...promptImage, ...promptAudio] }, canvas: { ...definition.canvas }, writingLayout: { ...definition.writingLayout }, writingDirection: definition.writingDirection, tools: { ...definition.tools }, completion: { ...definition.completion }, teacherReviewRequired: definition.teacherReviewRequired, allowRetry: definition.allowRetry, clearOnRetry: definition.clearOnRetry, hint: { type: definition.hint.type, media: definition.hint.type === "PLAY_PROMPT_AUDIO" ? promptAudio : definition.hint.type === "SHOW_PROMPT_IMAGE" ? promptImage : [] }, media: { promptImage, promptAudio, instructionAudio: previewMedia(definition.media.instructionAudioKey, media), supportingImage: previewMedia(definition.media.supportingImageKey, media), supportingVideo: previewMedia(definition.media.supportingVideoKey, media) } } }; }
export function freeHandwritingAuditSummary(configuration: FreeHandwritingConfiguration): { responseMode: FreeHandwritingResponseMode; promptLength: number; lineStyle: FreeHandwritingLineStyle; lineCount: number; minimumStrokeCount: number; minimumWritingRegionsUsed: number; teacherReviewRequired: boolean; hintType: FreeHandwritingHintType } { const definition = configuration.freeHandwriting; return { responseMode: definition.responseMode, promptLength: definition.prompt.text?.length ?? 0, lineStyle: definition.writingLayout.lineStyle, lineCount: definition.writingLayout.lineCount, minimumStrokeCount: definition.completion.minimumStrokeCount, minimumWritingRegionsUsed: definition.completion.minimumWritingRegionsUsed, teacherReviewRequired: definition.teacherReviewRequired, hintType: definition.hint.type }; }
