import { assertSafeStorageKey } from "../storage/local-storage.adapter.js";
import { jsonByteSize } from "../utils/safe-json-schema.js";

export const VOICE_RECORDING_MAX_BYTES = 16 * 1024;
export const VOICE_RECORDING_MAX_DEPTH = 8;
const UNSAFE = /(?:<\s*\/?\s*[a-z][^>]*>|\b(?:javascript|vbscript|data)\s*:|\bfunction\b|\beval\s*\(|\bscript\b|\bon[a-z]+\s*=|\b[a-z][a-z0-9+.-]*:\/\/)/i;
const FORBIDDEN = new Set(["__proto__", "prototype", "constructor"]);
export type VoiceRecordingIssueCode = "VOICE_RECORDING_CONTRACT_REQUIRED" | "VOICE_RECORDING_CONFIGURATION_INVALID" | "VOICE_RECORDING_CONFIGURATION_TOO_LARGE" | "VOICE_RECORDING_CONFIGURATION_TOO_DEEP" | "VOICE_RECORDING_UNSAFE_CONTENT" | "VOICE_RECORDING_UNSUPPORTED_FIELD" | "VOICE_RECORDING_PROMPT_INVALID" | "VOICE_RECORDING_RECORDING_INVALID" | "VOICE_RECORDING_INSTRUCTIONS_INVALID" | "VOICE_RECORDING_MEDIA_INVALID";
export class VoiceRecordingContractError extends Error { constructor(readonly issues: readonly VoiceRecordingIssueCode[]) { super("Kontrak Voice Recording tidak sah."); this.name = "VoiceRecordingContractError"; } }
export interface VoiceRecordingConfiguration { voiceRecording: { prompt: { title: string | null; content: string; media: Array<{ key: string }> }; recording: { minimumDurationSeconds: number; maximumDurationSeconds: number; maximumAttempts: number; allowPlayback: boolean; allowReRecord: boolean; autoStop: boolean; autoSubmitOnFinish: boolean; required: boolean }; instructions: string | null; }; }
export interface VoiceRecordingPreviewMediaDescriptor { url: string | null; mimeType?: string | null; altText?: string | null; label?: string | null; }
function fail(...issues: VoiceRecordingIssueCode[]): never { throw new VoiceRecordingContractError(issues); }
function obj(value: unknown, issue: VoiceRecordingIssueCode = "VOICE_RECORDING_CONTRACT_REQUIRED"): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) fail(issue); const p = Object.getPrototypeOf(value); if (p !== Object.prototype && p !== null) fail(issue); return value as Record<string, unknown>; }
function safeJson(value: unknown, depth = 0, seen = new WeakSet<object>()): void { if (depth > VOICE_RECORDING_MAX_DEPTH) fail("VOICE_RECORDING_CONFIGURATION_TOO_DEEP"); if (value === null || typeof value === "boolean") return; if (typeof value === "number") { if (!Number.isFinite(value)) fail("VOICE_RECORDING_CONFIGURATION_INVALID"); return; } if (typeof value === "string") { if (UNSAFE.test(value)) fail("VOICE_RECORDING_UNSAFE_CONTENT"); return; } if (!value || typeof value !== "object" || value instanceof Date || Buffer.isBuffer(value) || seen.has(value)) fail("VOICE_RECORDING_CONFIGURATION_INVALID"); seen.add(value); if (Array.isArray(value)) { for (const entry of value) safeJson(entry, depth + 1, seen); return; } for (const [key, entry] of Object.entries(obj(value, "VOICE_RECORDING_CONFIGURATION_INVALID"))) { if (FORBIDDEN.has(key) || UNSAFE.test(key)) fail("VOICE_RECORDING_UNSAFE_CONTENT"); safeJson(entry, depth + 1, seen); } }
function allowed(value: Record<string, unknown>, names: readonly string[]): void { for (const key of Object.keys(value)) if (!names.includes(key)) fail("VOICE_RECORDING_UNSUPPORTED_FIELD"); }
function text(value: unknown, issue: VoiceRecordingIssueCode, max: number): string { if (typeof value !== "string") fail(issue); const result = value.trim().normalize("NFC"); if (!result || result.length > max || UNSAFE.test(result) || result.includes("{{") || result.includes("}}")) fail(issue); return result; }
function bool(value: unknown): boolean { if (typeof value !== "boolean") fail("VOICE_RECORDING_RECORDING_INVALID"); return value; }
function parseMedia(value: unknown): Array<{ key: string }> { if (!Array.isArray(value) || value.length > 20) fail("VOICE_RECORDING_MEDIA_INVALID"); const entries = value.map((entry) => { const media = obj(entry, "VOICE_RECORDING_MEDIA_INVALID"); allowed(media, ["key"]); if (typeof media.key !== "string" || media.key !== media.key.trim() || !media.key || media.key.length > 512 || UNSAFE.test(media.key)) fail("VOICE_RECORDING_MEDIA_INVALID"); try { assertSafeStorageKey(media.key); } catch { fail("VOICE_RECORDING_MEDIA_INVALID"); } return { key: media.key }; }); if (new Set(entries.map((entry) => entry.key)).size !== entries.length) fail("VOICE_RECORDING_MEDIA_INVALID"); return entries; }
export function validateVoiceRecordingConfiguration(value: unknown): VoiceRecordingConfiguration { if (jsonByteSize(value) > VOICE_RECORDING_MAX_BYTES) fail("VOICE_RECORDING_CONFIGURATION_TOO_LARGE"); safeJson(value); const config = obj(value); allowed(config, ["voiceRecording"]); const definition = obj(config.voiceRecording); allowed(definition, ["prompt", "recording", "instructions"]); const rawPrompt = obj(definition.prompt, "VOICE_RECORDING_PROMPT_INVALID"); allowed(rawPrompt, ["title", "content", "media"]); const prompt = { title: rawPrompt.title === undefined || rawPrompt.title === null ? null : text(rawPrompt.title, "VOICE_RECORDING_PROMPT_INVALID", 300), content: text(rawPrompt.content, "VOICE_RECORDING_PROMPT_INVALID", 3_000), media: parseMedia(rawPrompt.media) }; const rawRecording = obj(definition.recording, "VOICE_RECORDING_RECORDING_INVALID"); allowed(rawRecording, ["minimumDurationSeconds", "maximumDurationSeconds", "maximumAttempts", "allowPlayback", "allowReRecord", "autoStop", "autoSubmitOnFinish", "required"]); if (typeof rawRecording.minimumDurationSeconds !== "number" || !Number.isInteger(rawRecording.minimumDurationSeconds) || rawRecording.minimumDurationSeconds < 1 || rawRecording.minimumDurationSeconds > 600 || typeof rawRecording.maximumDurationSeconds !== "number" || !Number.isInteger(rawRecording.maximumDurationSeconds) || rawRecording.maximumDurationSeconds < 5 || rawRecording.maximumDurationSeconds > 900 || rawRecording.maximumDurationSeconds < rawRecording.minimumDurationSeconds || typeof rawRecording.maximumAttempts !== "number" || !Number.isInteger(rawRecording.maximumAttempts) || rawRecording.maximumAttempts < 1 || rawRecording.maximumAttempts > 20) fail("VOICE_RECORDING_RECORDING_INVALID"); const recording = { minimumDurationSeconds: rawRecording.minimumDurationSeconds, maximumDurationSeconds: rawRecording.maximumDurationSeconds, maximumAttempts: rawRecording.maximumAttempts, allowPlayback: bool(rawRecording.allowPlayback), allowReRecord: bool(rawRecording.allowReRecord), autoStop: bool(rawRecording.autoStop), autoSubmitOnFinish: bool(rawRecording.autoSubmitOnFinish), required: bool(rawRecording.required) }; const instructions = definition.instructions === undefined || definition.instructions === null ? null : text(definition.instructions, "VOICE_RECORDING_INSTRUCTIONS_INVALID", 1_000); return { voiceRecording: { prompt, recording, instructions } }; }
export function voiceRecordingMediaKeys(configuration: VoiceRecordingConfiguration): string[] { return configuration.voiceRecording.prompt.media.map((media) => media.key); }
export async function validateVoiceRecordingMedia(configuration: VoiceRecordingConfiguration, exists: (key: string) => Promise<void>): Promise<void> { for (const key of voiceRecordingMediaKeys(configuration)) { try { await exists(key); } catch { fail("VOICE_RECORDING_MEDIA_INVALID"); } } }
function safePreviewMediaText(value: string | null | undefined): string | null { if (typeof value !== "string" || UNSAFE.test(value) || /(?:^|[\\/])(?:private|var|tmp|users|home)(?:[\\/]|$)/i.test(value)) return null; return value; }
export function voiceRecordingPreviewConfiguration(configuration: VoiceRecordingConfiguration, media: ReadonlyMap<string, VoiceRecordingPreviewMediaDescriptor>) { const definition = configuration.voiceRecording; return { voiceRecording: { prompt: { title: definition.prompt.title, content: definition.prompt.content, media: definition.prompt.media.map((entry) => { const descriptor = media.get(entry.key); return { key: entry.key, url: descriptor?.url ?? null, mimeType: descriptor?.mimeType ?? null, altText: safePreviewMediaText(descriptor?.altText), label: safePreviewMediaText(descriptor?.label) }; }) }, recording: { ...definition.recording }, instructions: definition.instructions } }; }
export function voiceRecordingAuditSummary(configuration: VoiceRecordingConfiguration): { minimumDurationSeconds: number; maximumDurationSeconds: number; maximumAttempts: number } { const recording = configuration.voiceRecording.recording; return { minimumDurationSeconds: recording.minimumDurationSeconds, maximumDurationSeconds: recording.maximumDurationSeconds, maximumAttempts: recording.maximumAttempts }; }
