import { AiReviewStatus, Prisma, UserRole } from "@prisma/client";
import { prisma } from "../../config/prisma.js";
import { AppError } from "../../errors/app-error.js";
import type { AiContext } from "./ai.service.js";
const fail = (code: string, status: number, message: string) => new AppError(code, status, message);
async function outputForAccess(id: string, context: AiContext) { const output = await prisma.aiGeneratedOutput.findUnique({ where: { id }, include: { aiRequest: true } }); if (!output) throw fail("AI_OUTPUT_NOT_FOUND", 404, "Output AI tidak ditemui."); const allowed = context.actor.role === UserRole.SUPER_ADMIN || (context.actor.role === UserRole.ADMIN && (context.actor.schoolId === null || context.actor.schoolId === output.aiRequest.schoolId)) || output.aiRequest.requestedByUserId === context.actor.userId; if (!allowed) throw fail("AI_REQUEST_ACCESS_DENIED", 403, "Anda tidak dibenarkan mengakses output AI ini."); return output; }
export async function listAiOutputs(context: AiContext) { const where = context.actor.role === UserRole.SUPER_ADMIN ? {} : context.actor.role === UserRole.ADMIN ? { aiRequest: { schoolId: context.actor.schoolId ?? undefined } } : { aiRequest: { requestedByUserId: context.actor.userId } }; return prisma.aiGeneratedOutput.findMany({ where, select: { id: true, reviewStatus: true, disposition: true, safeSummary: true, createdAt: true, aiRequest: { select: { id: true, featureType: true, status: true, createdAt: true } } }, orderBy: { createdAt: "desc" }, take: 100 }); }
export async function getAiOutput(id: string, context: AiContext) { const output = await outputForAccess(id, context); return { id: output.id, reviewStatus: output.reviewStatus, disposition: output.disposition, structuredOutput: output.structuredOutput, safeSummary: output.safeSummary, createdAt: output.createdAt }; }
export async function approveAiOutput(id: string, input: { reviewNotes?: string; editedStructuredOutput?: Record<string, unknown> }, context: AiContext) { const output = await outputForAccess(id, context); if (output.reviewStatus !== AiReviewStatus.PENDING_REVIEW) throw fail("AI_OUTPUT_ALREADY_REVIEWED", 409, "Output AI telah disemak."); return prisma.aiGeneratedOutput.update({ where: { id }, data: { reviewStatus: input.editedStructuredOutput ? AiReviewStatus.EDITED : AiReviewStatus.APPROVED, structuredOutput: input.editedStructuredOutput as Prisma.InputJsonValue | undefined, reviewNotes: input.reviewNotes ?? null, reviewedByUserId: context.actor.userId, approvedAt: new Date() } }); }
export async function rejectAiOutput(id: string, reviewNotes: string, context: AiContext) { const output = await outputForAccess(id, context); if (output.reviewStatus !== AiReviewStatus.PENDING_REVIEW) throw fail("AI_OUTPUT_ALREADY_REVIEWED", 409, "Output AI telah disemak."); return prisma.aiGeneratedOutput.update({ where: { id }, data: { reviewStatus: AiReviewStatus.REJECTED, reviewNotes, reviewedByUserId: context.actor.userId, rejectedAt: new Date() } }); }
export async function archiveAiOutput(id: string, context: AiContext) { const output = await outputForAccess(id, context); if (context.actor.role !== UserRole.SUPER_ADMIN && output.aiRequest.requestedByUserId !== context.actor.userId) throw fail("AI_REQUEST_ACCESS_DENIED", 403, "Anda tidak dibenarkan mengarkib output AI ini."); return prisma.aiGeneratedOutput.update({ where: { id }, data: { reviewStatus: AiReviewStatus.ARCHIVED, archivedAt: new Date() } }); }
