CREATE TYPE "AiFeatureType" AS ENUM ('QUESTION_DRAFT', 'ACTIVITY_DRAFT', 'READING_PASSAGE_DRAFT', 'READING_COMPREHENSION_DRAFT', 'CURRICULUM_ALIGNMENT', 'TEXT_SIMPLIFICATION', 'FEEDBACK_DRAFT', 'PARENT_SUMMARY_DRAFT', 'PRACTICE_SUGGESTION', 'AUDIO_TRANSCRIPTION', 'AUDIO_READING_ANALYSIS', 'DUPLICATE_DETECTION');
CREATE TYPE "AiRequestStatus" AS ENUM ('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'BLOCKED', 'CANCELLED', 'EXPIRED');
CREATE TYPE "AiReviewStatus" AS ENUM ('NOT_REQUIRED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'EDITED', 'ARCHIVED');
CREATE TYPE "AiProvider" AS ENUM ('GOOGLE_GEMINI');
CREATE TYPE "AiRiskLevel" AS ENUM ('LOW', 'MEDIUM', 'HIGH');
CREATE TYPE "AiOutputDisposition" AS ENUM ('DRAFT_ONLY', 'ADVISORY_ONLY', 'SAFE_SUMMARY');

CREATE TABLE "ai_prompt_templates" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "code" TEXT NOT NULL, "version" INTEGER NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "featureType" "AiFeatureType" NOT NULL, "systemInstruction" TEXT NOT NULL, "promptTemplate" TEXT NOT NULL, "outputSchema" JSONB NOT NULL, "modelAlias" TEXT NOT NULL, "temperature" DECIMAL(3,2), "maximumOutputTokens" INTEGER, "riskLevel" "AiRiskLevel" NOT NULL, "requiresHumanReview" BOOLEAN NOT NULL DEFAULT true, "isActive" BOOLEAN NOT NULL DEFAULT false, "createdByUserId" UUID NOT NULL, "activatedByUserId" UUID, "activatedAt" TIMESTAMP(3), "archivedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ai_prompt_templates_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ai_requests" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "featureType" "AiFeatureType" NOT NULL, "provider" "AiProvider" NOT NULL DEFAULT 'GOOGLE_GEMINI', "promptTemplateId" UUID NOT NULL, "requestedByUserId" UUID NOT NULL, "schoolId" UUID, "studentId" UUID, "assignmentId" UUID, "assessmentId" UUID, "curriculumVersionId" UUID, "programmeId" UUID, "remedialSkillId" UUID, "status" "AiRequestStatus" NOT NULL DEFAULT 'QUEUED', "riskLevel" "AiRiskLevel" NOT NULL, "inputSummary" JSONB, "providerRequestId" TEXT, "modelAlias" TEXT NOT NULL, "inputTokenCount" INTEGER, "outputTokenCount" INTEGER, "totalTokenCount" INTEGER, "estimatedCostMyr" DECIMAL(12,6), "latencyMs" INTEGER, "retryCount" INTEGER NOT NULL DEFAULT 0, "blockedReason" TEXT, "failureCode" TEXT, "startedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "failedAt" TIMESTAMP(3), "expiresAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ai_requests_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ai_generated_outputs" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "aiRequestId" UUID NOT NULL, "reviewStatus" "AiReviewStatus" NOT NULL DEFAULT 'PENDING_REVIEW', "disposition" "AiOutputDisposition" NOT NULL, "structuredOutput" JSONB NOT NULL, "safeSummary" TEXT, "validationIssues" JSONB, "reviewedByUserId" UUID, "reviewNotes" TEXT, "approvedAt" TIMESTAMP(3), "rejectedAt" TIMESTAMP(3), "archivedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ai_generated_outputs_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ai_usage_daily" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "usageDate" DATE NOT NULL, "schoolId" UUID, "featureType" "AiFeatureType" NOT NULL, "requestCount" INTEGER NOT NULL DEFAULT 0, "blockedCount" INTEGER NOT NULL DEFAULT 0, "failedCount" INTEGER NOT NULL DEFAULT 0, "inputTokenCount" BIGINT NOT NULL DEFAULT 0, "outputTokenCount" BIGINT NOT NULL DEFAULT 0, "totalTokenCount" BIGINT NOT NULL DEFAULT 0, "estimatedCostMyr" DECIMAL(14,6) NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ai_usage_daily_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "ai_prompt_templates_code_version_key" ON "ai_prompt_templates"("code", "version"); CREATE INDEX "ai_prompt_templates_featureType_idx" ON "ai_prompt_templates"("featureType"); CREATE INDEX "ai_prompt_templates_isActive_idx" ON "ai_prompt_templates"("isActive"); CREATE INDEX "ai_prompt_templates_riskLevel_idx" ON "ai_prompt_templates"("riskLevel"); CREATE INDEX "ai_requests_featureType_idx" ON "ai_requests"("featureType"); CREATE INDEX "ai_requests_status_idx" ON "ai_requests"("status"); CREATE INDEX "ai_requests_requestedByUserId_idx" ON "ai_requests"("requestedByUserId"); CREATE INDEX "ai_requests_schoolId_idx" ON "ai_requests"("schoolId"); CREATE INDEX "ai_requests_studentId_idx" ON "ai_requests"("studentId"); CREATE INDEX "ai_requests_createdAt_idx" ON "ai_requests"("createdAt"); CREATE INDEX "ai_requests_schoolId_createdAt_idx" ON "ai_requests"("schoolId", "createdAt"); CREATE UNIQUE INDEX "ai_generated_outputs_aiRequestId_key" ON "ai_generated_outputs"("aiRequestId"); CREATE INDEX "ai_generated_outputs_reviewStatus_idx" ON "ai_generated_outputs"("reviewStatus"); CREATE INDEX "ai_generated_outputs_disposition_idx" ON "ai_generated_outputs"("disposition"); CREATE INDEX "ai_generated_outputs_createdAt_idx" ON "ai_generated_outputs"("createdAt"); CREATE UNIQUE INDEX "ai_usage_daily_usageDate_schoolId_featureType_key" ON "ai_usage_daily"("usageDate", "schoolId", "featureType"); CREATE INDEX "ai_usage_daily_usageDate_idx" ON "ai_usage_daily"("usageDate"); CREATE INDEX "ai_usage_daily_schoolId_idx" ON "ai_usage_daily"("schoolId");

ALTER TABLE "ai_prompt_templates" ADD CONSTRAINT "ai_prompt_templates_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "ai_prompt_templates" ADD CONSTRAINT "ai_prompt_templates_activatedByUserId_fkey" FOREIGN KEY ("activatedByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "ai_requests" ADD CONSTRAINT "ai_requests_promptTemplateId_fkey" FOREIGN KEY ("promptTemplateId") REFERENCES "ai_prompt_templates"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "ai_requests" ADD CONSTRAINT "ai_requests_requestedByUserId_fkey" FOREIGN KEY ("requestedByUserId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "ai_requests" ADD CONSTRAINT "ai_requests_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "ai_requests" ADD CONSTRAINT "ai_requests_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "ai_requests" ADD CONSTRAINT "ai_requests_assignmentId_fkey" FOREIGN KEY ("assignmentId") REFERENCES "assignments"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "ai_requests" ADD CONSTRAINT "ai_requests_assessmentId_fkey" FOREIGN KEY ("assessmentId") REFERENCES "assessments"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "ai_requests" ADD CONSTRAINT "ai_requests_curriculumVersionId_fkey" FOREIGN KEY ("curriculumVersionId") REFERENCES "curriculum_versions"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "ai_requests" ADD CONSTRAINT "ai_requests_programmeId_fkey" FOREIGN KEY ("programmeId") REFERENCES "curriculum_programmes"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "ai_requests" ADD CONSTRAINT "ai_requests_remedialSkillId_fkey" FOREIGN KEY ("remedialSkillId") REFERENCES "remedial_skills"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "ai_generated_outputs" ADD CONSTRAINT "ai_generated_outputs_aiRequestId_fkey" FOREIGN KEY ("aiRequestId") REFERENCES "ai_requests"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ai_generated_outputs" ADD CONSTRAINT "ai_generated_outputs_reviewedByUserId_fkey" FOREIGN KEY ("reviewedByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "ai_usage_daily" ADD CONSTRAINT "ai_usage_daily_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE SET NULL ON UPDATE CASCADE;
