import { Link, useParams } from "react-router-dom";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/shared/PageHeader";
import { ErrorState } from "@/components/shared/ErrorState";
import { LoadingSpinner } from "@/components/shared/LoadingSpinner";
import { ParentCards, ParentMetrics } from "@/features/parent/components/ParentComponents";
import { useParentChildList, useParentDashboard, useParentList, useParentProfile, useParentProgress, useParentReport } from "@/features/parent/hooks/use-parent";
import type { ParentResource } from "@/features/parent/types/parent.types";
import { isParentRecord, parentSafeEntries, parentText } from "@/features/parent/utils/parent-record";
function State({loading,error,retry}:{loading:boolean;error:unknown;retry:()=>void}){if(loading)return <div className="grid min-h-48 place-items-center"><LoadingSpinner label="Memuatkan..."/></div>;if(error)return <ErrorState title="Tidak dapat memuatkan data" description="Sila cuba lagi." actionLabel="Cuba lagi" onAction={retry}/>;return null}
export function ParentDashboardPage(){const q=useParentDashboard();const data=q.data??{};const children=Array.isArray(data.children)?data.children.filter(isParentRecord):[];return <main className="space-y-6"><PageHeader title="Portal Ibu Bapa" description="Pantau kemajuan anak anda dengan selamat."/><State loading={q.isLoading} error={q.error} retry={()=>void q.refetch()}/>{!q.isLoading&&!q.error?<><ParentMetrics items={[{label:"Anak Dipautkan",value:data.linkedChildrenCount},{label:"Aktiviti",value:children.length}]}/><div className="grid gap-4 md:grid-cols-2">{children.map(child=><Card key={parentText(child.id)}><CardHeader><CardTitle>{parentText(child.fullName)}</CardTitle><CardDescription>{parentText(isParentRecord(child.class)?child.class.className:"Kelas")}</CardDescription></CardHeader><CardContent><Button asChild><Link to={`/ibu-bapa/anak/${parentText(child.id)}`}>Lihat kemajuan</Link></Button></CardContent></Card>)}</div></>:null}</main>}
export function ParentChildrenPage(){const q=useParentDashboard();const children=Array.isArray(q.data?.children)?q.data.children.filter(isParentRecord):[];return <main className="space-y-6"><PageHeader title="Anak Saya"/><State loading={q.isLoading} error={q.error} retry={()=>void q.refetch()}/>{!q.isLoading&&!q.error?<div className="grid gap-4 md:grid-cols-2">{children.map(child=><Card key={parentText(child.id)}><CardHeader><CardTitle>{parentText(child.fullName)}</CardTitle><CardDescription>{parentText(isParentRecord(child.class)?child.class.className:"—")}</CardDescription></CardHeader><CardContent><Button asChild><Link to={`/ibu-bapa/anak/${parentText(child.id)}`}>Pilih anak</Link></Button></CardContent></Card>)}</div>:null}</main>}
export function ParentChildPage(){const {studentId=""}=useParams();const q=useParentProgress(studentId);return <main className="space-y-6"><PageHeader title="Kemajuan Anak"/><State loading={q.isLoading} error={q.error} retry={()=>void q.refetch()}/>{q.data?<ParentMetrics items={[{label:"Kemajuan Pembelajaran",value:q.data.learningProgress??q.data.progress},{label:"Kemahiran",value:Array.isArray(q.data.structures)?q.data.structures.length:"—"}]}/>:null}<div className="flex flex-wrap gap-2"><Button asChild><Link to={`/ibu-bapa/tugasan?studentId=${studentId}`}>Tugasan</Link></Button><Button variant="outline" asChild><Link to={`/ibu-bapa/laporan?studentId=${studentId}`}>Laporan</Link></Button></div></main>}
export function ParentChildListPage({kind}:{kind:ParentResource}){const params=new URLSearchParams(location.search);const studentId=params.get("studentId")??"";const q=useParentChildList(kind,studentId);return <main className="space-y-6"><PageHeader title={{assignments:"Tugasan",submissions:"Penghantaran",assessments:"Keputusan"}[kind]} description={studentId?"Maklumat anak yang dipautkan sahaja.":"Pilih anak daripada halaman Anak Saya."}/>{!studentId?<p className="text-muted-foreground">Sila pilih anak dahulu.</p>:<><State loading={q.isLoading} error={q.error} retry={()=>void q.refetch()}/>{!q.isLoading&&!q.error?<ParentCards rows={q.data??[]} childId={studentId} kind={kind}/>:null}</>}</main>}
export function ParentProgressPage(){const params=new URLSearchParams(location.search);const id=params.get("studentId")??"";const q=useParentProgress(id);return <main className="space-y-6"><PageHeader title="Kemajuan"/><State loading={q.isLoading} error={q.error} retry={()=>void q.refetch()}/>{q.data?<ParentMetrics items={[{label:"Kemajuan Pembelajaran",value:q.data.learningProgress??q.data.progress}]}/>:null}</main>}
export function ParentReportPage(){const params=new URLSearchParams(location.search);const id=params.get("studentId")??"";const q=useParentReport(id);return <main className="space-y-6"><PageHeader title="Laporan Anak"/><State loading={q.isLoading} error={q.error} retry={()=>void q.refetch()}/>{q.data?<Card><CardContent className="grid gap-3 p-6 sm:grid-cols-2">{parentSafeEntries(q.data).map(([k,v])=><div key={k}><p className="text-xs uppercase text-muted-foreground">{k}</p><p>{typeof v==="object"&&v!==null?"Maklumat tersedia":parentText(v)}</p></div>)}</CardContent></Card>:null}</main>}
export function ParentSimpleListPage({path,key,title}:{path:string;key:string;title:string}){const q=useParentList(path,key);return <main className="space-y-6"><PageHeader title={title}/><State loading={q.isLoading} error={q.error} retry={()=>void q.refetch()}/>{!q.isLoading&&!q.error?<ParentCards rows={q.data??[]} childId="" kind={key}/>:null}</main>}
export function ParentProfilePage(){const q=useParentProfile();return <main className="space-y-6"><PageHeader title="Profil Saya"/><State loading={q.isLoading} error={q.error} retry={()=>void q.refetch()}/>{q.data?<Card><CardContent className="grid gap-3 p-6 sm:grid-cols-2">{parentSafeEntries(q.data).map(([k,v])=><div key={k}><p className="text-xs uppercase text-muted-foreground">{k}</p><p>{typeof v==="object"&&v!==null?"Maklumat tersedia":parentText(v)}</p></div>)}</CardContent></Card>:null}</main>}
